### ISSUE TITLE
Error in during SIGMA execution.

### ISSUE THREAD

**Issue by Kirk3gaard** [CSB5/OPERA-MS#10]
Hi

First of all I would like to thank you for publishing a tool for metagenomic assembly with nanopore reads I am really excited to try it out. I have tried running the OPERA-MS on some of our own data but it failed with the following error:

```
Error in during SIGMA execution. Please see OPERA_assembly//intermediate_files/sigma/log.out and OPERA_assembly//intermediate_files/sigma/log.err for details.
```

So I looked in the log.out and it is empty and the log.err contains the following:

```
Loading contig information from OPERA_assembly/intermediate_files/coverage_estimation/contigs_340_80...
Error opening file: OPERA_assembly/intermediate_files/coverage_estimation/contigs_340_80
```

I do not know how to act on this error message. Running our installation on the test data set works fine and I have only swapped the read files in the config to our own fastqs + adjusted the number of CPUs. Do you have any idea how I can fix/troubleshoot this error?

I cannot seem to get OPERA to output a version number or find the current version number on github. Can you give me a hint and I will provide you with my OPERA version. 

Best regards
Rasmus

**Comment by dbertran78** [comment]
Dear Rasmus,
Thank you very much for your interest in OPERA-MS.
I am sorry for the late reply, I just came back from vacation.

I will need you the detailed logs to identify the problem.
Could you please run the following command line:
```
opera_res= OPERA_assembly/intermediate_files/
mkdir OPERA-MS-LOG/;
cp --parent $opera_res/*err $opera_res/*/*err $opera_res/*/*out $opera_res/strain_analysis/STRAIN/log* $opera_res/strain_analysis/STRAIN/opera.config OPERA-MS-LOG/
tar -cvzf OPERA-MS-LOG.tar.gz OPERA-MS-LOG/
```

Can you send me the OPERA-MS config file and OPERA-MS-LOG.tar.gz at dbertran78@gmail.com

Thank you,

Denis

**Comment by Kirk3gaard** [comment]
Dear Denis

No worries it is not as if having a github means that people should expect expect 24 hour customer support. I am just glad to get a reply, and thankful that you will look into this issue :D 

I have sent you an email with the log files. 

Best regards
Rasmus

**Comment by dbertran78** [comment]
Dear Rasmus,
It seems that the error occurred during the coverage estimation. And unfortunately, I did not save the log file for this step.
Could you please run the following commands:
```
rm /space/users/malber06/2017_long_read/digester/alternativeassemblers/OPERA/OPERA_assembly//contigs.bam.sam 
/space/sharedbin_ubuntu_14_04/software/OPERA-MS/2018-11-20-foss-2018a/bin/sigma /space/users/malber06/2017_long_read/digester/alternativeassemblers/OPERA/OPERA_assembly/intermediate_files/coverage_estimation/sigma.config > cov_estimation.out 2> cov_estimation.err
```
And send me the files **cov_estimation.out**  and **cov_estimation.err**.

Thank you for your help,

--- Denis

**Comment by dbertran78** [comment]
Solved offline.
