### ISSUE TITLE
Infinite loop in cluster_strain.pl

### ISSUE THREAD

**Issue by johnomics** [CSB5/OPERA-MS#11]
Hello,

Thank you for writing OPERA-MS, it looks like a very useful package. Unfortunately, it got stuck in an infinite loop at the cluster_strain.pl stage.

Here's my config file:
```
OUTPUT_DIR output
LONG_READ reads.fastq
ILLUMINA_READ_1 R1.fastq.gz
ILLUMINA_READ_2 R2.fastq.gz
NUM_PROCESSOR 60
LONG_READ_MAPPER minimap2
CONTIG_WINDOW_LEN 340
CONTIG_EDGE_LEN 80
KMER_SIZE 60
CONTIGS_FILE output/intermediate_files/megahit_assembly/final.contigs.fa
```

The strain_analysis/assembly.cmd file is running through xargs, with only one of 12 cluster_strain.pl jobs still running. This job is repeatedly outputting the following messages:

```
 *** [1]   45.03429  130.60357  323.13447  586.97311 1083.75036
 *** MODE DETECTED 45.03429 130.60357 323.13447 586.97311 1083.75036
 estimate_mean 1083.75036 5938222.53552254
MEAN ESTIMATION BASED 1083.7505425042ON MODE 1083.75036 AND DISPERTION 5938222.53552254
ESTIMATED CONFIDANCE INTERVAL FOR  1083.75036 -> [1017 1152]
 estimate_mean 586.97311 5938222.53552254
MEAN ESTIMATION BASED 586.973208846617ON MODE 586.97311 AND DISPERTION 5938222.53552254
ESTIMATED CONFIDANCE INTERVAL FOR  586.97311 -> [538 637]
 *** Mode distribution evaluation : 586.97311 sequence_size_in_h_mode_distribution: 565420 mean_cov_in_dist 588.159951894167  estimated_mean_value 586.973208846617 mean_cov_in_dist/estimated_mean_value 1.00202180104588
 estimate_mean 323.13447 5938222.53552254
MEAN ESTIMATION BASED 323.134524416035ON MODE 323.13447 AND DISPERTION 5938222.53552254
ESTIMATED CONFIDANCE INTERVAL FOR  323.13447 -> [287 361]
 *** Mode distribution evaluation : 323.13447 sequence_size_in_h_mode_distribution: 807840 mean_cov_in_dist 327.531565656566  estimated_mean_value 323.134524416035 mean_cov_in_dist/estimated_mean_value 1.01360746348128
 estimate_mean 130.60357 5938222.53552254
MEAN ESTIMATION BASED 130.603591993718ON MODE 130.60357 AND DISPERTION 5938222.53552254
ESTIMATED CONFIDANCE INTERVAL FOR  130.60357 -> [108 155]
 *** Mode distribution evaluation : 130.60357 sequence_size_in_h_mode_distribution: 1242360 mean_cov_in_dist 131.292829775588  estimated_mean_value 130.603591993718 mean_cov_in_dist/estimated_mean_value 1.00527732638398
 estimate_mean 45.03429 5938222.53552254
MEAN ESTIMATION BASED 45.0342975838009ON MODE 45.03429 AND DISPERTION 5938222.53552254
ESTIMATED CONFIDANCE INTERVAL FOR  45.03429 -> [32 59]
 *** Mode distribution evaluation : 45.03429 sequence_size_in_h_mode_distribution: 491980 mean_cov_in_dist 43.8942639944713  estimated_mean_value 45.0342975838009 mean_cov_in_dist/estimated_mean_value 0.974685214370043
```

It looks like `while($mode_accepted==-1)` at line 108 of cluster_strain.pl is never passed, because the condition at lines 157/158 is never true:
```
        if((0.70 < ($mean_cov_in_dist  / $strain_mean_value) && ($mean_cov_in_dist  / $strain_mean_value) < 1.3) && #the mean estimate and the mean obtain by the confidance interval are comparable => good fitting
            $sequence_size_in_h_mode_distribution > $reference_size*0.5)
```

As shown in the log above, mean_cov_in_dist/estimated_mean_value is always between 0.70 and 1.3. However, reference_size (from the assembly.cmd script) is 5163189:
```
perl /install/OPERA-MS/bin/cluster_strain.pl /files/output/intermediate_files/strain_analysis/Bacteroides_vulgatus 5163189 23.807457 11.859699 /install/OPERA-MS/
```

So it looks like `sequence_size_in_h_mode_distribution`, also shown in the logs above, is never above half of the reference size.

Any suggestions on how to resolve this?

Many thanks
John

**Comment by dbertran78** [comment]
Hi John,
Thank you for highlighting this problem.
I have just pushed a new version of OPERA-MS that should solve the infinite loop.
Notice that in your case, the strain de-convolution module is not able to separate the Bacteroides_vulgatus strains due to their similarity in coverage. In this case, the 2 strains will be assembled together which may lead to the assembly of chimeric contigs for this species (contigs that contains sequences from the different strains).
Please give it a try again on your sample, and feel free to update me if you encounter other issues.

Best regards,

--- Denis

**Comment by johnomics** [comment]
Thank you very much for the update. I have restarted the assembly from the long read mapping stage and will let you know how it goes.
