### ISSUE TITLE
MASH run fails

### ISSUE THREAD

**Issue by johnomics** [CSB5/OPERA-MS#12]
I'm running commit 7999fdb to test issue https://github.com/CSB5/OPERA-MS/issues/11 but discovered another issue. This run has failed at the MASH stage. No processes are running; the last message from the main process, written at 03:37, is the sequence_similarity_clustering.pl command, there are no error messages in intermediate_files/reference_mapping/log.err, just the xargs command, and intermediate_files/reference_mapping/MASH/log.txt is empty.

There are 183904 commands in the cmd.txt file, 183904 FASTAs in the MASH folder, but only 170861 dat files:
```
[asm/intermediate_files/reference_mapping/MASH] $ wc -l cmd.txt
183904 cmd.txt
[asm/intermediate_files/reference_mapping/MASH] $ find -type f -name "*.fa" | wc -l
183904
[asm/intermediate_files/reference_mapping/MASH] $ find -type f -name "*dat" | wc -l
170861
```

Last FASTA file was written at 03:46 and last DAT file at 04:14.

How can I get this started again? Is there a way to run from this stage without re-running the previous stages?

Thanks
John

**Comment by dbertran78** [comment]
Hi John,
Did you start a new run (new output directory), or did you use the same output directory as in your previous experiment.
As you mentioned no process were running, but did the code crash, or did you manually stopped the execution?

You can restart the experiment at that stage using the following command:
```
OPERA-MS.pl file.config REF_CLUSTERING+
```

**Comment by johnomics** [comment]
It was using the previous output directory, but I deleted all the files except for the megahit assembly, and then used the megahit assembly as the contigs file. There are lib_1_bundles, coverage_estimation, scaffolds, long-read-mapping and sigma folders with no errors that I can see. The code crashed, I didn't manually stop anything.

I have rerun the job from REF_CLUSTERING and got a similar result:
```
[reference_mapping/MASH] 2018-12-17 22:43 $ wc -l cmd.txt
183904 cmd.txt
[reference_mapping/MASH] 2018-12-17 22:30 $ ls -lrt > filelist.txt
[reference_mapping/MASH] 2018-12-17 22:43 $ grep -c fa filelist.txt
183904
[reference_mapping/MASH] 2018-12-17 22:42 $ grep -c dat filelist.txt
177043
```

I'm running on a 64 core, 256 GB RAM machine, with OPERA-MS configured to use 60 cores. The machine was consistently running 50-60 MASH jobs during the run, and was nowhere near to running out of memory.

I'm not sure if it's a small subset of MASH jobs failing when they run, or if it's the master job that stops running and fails to run some of the jobs. Any thoughts greatly appreciated. I'll try to find time to dig into this some more in the next few days.

**Comment by dbertran78** [comment]
From what I see, one possibility is that MASH crashed (due for example to a segmentation fault) and did produce any errors, which is why the log.txt is empty.
This can be due to the generation of a corrupted .fa file.
I should be able to figure that out if you send me the following files:
```
reference_mapping/MASH/cmd.txt
wc -l reference_mapping/MASH/*fa > fa_nb_line.dat
sigma/clusters
```

**Comment by johnomics** [comment]
Thanks - here are the files:
[opera-ms_mash_files.zip](https://github.com/CSB5/OPERA-MS/files/2689953/opera-ms_mash_files.zip)

This is from another run where only 80269 dat files were produced. I edited the sequence_similarity_clustering.pl script to write MASH output to log files (as seen in the cmd.txt file), but no output was produced in any of the log files.

**Comment by johnomics** [comment]
Any thoughts on this? I'm still interested in getting OPERA-MS running if possible. Thanks.

**Comment by dbertran78** [comment]
Hi John,
I checked the files that you sent me.
My guess was that one of the fa file will be corrupted (missing line) and that MASH to crash, but it seems that the fa files  have all the correct number of lines.

>> I edited the sequence_similarity_clustering.pl script to write MASH output to log files (as seen in the cmd.txt file), but no output was produced in any of the log files.

The log files are empty because mash do not output any thing when the run work well, and it can crash (segmentation fault) without reporting any errors in some cases.

If it is a problem with mash, the crash should have happen on of one of the latest .dat file produced.
If you still have the 2 OPERA-MS runs, can you execute, for each of them, the following command:
ls -lrt reference_mapping/MASH/.dat > time_out_creation.txt

Can you send me both files, that i could identify the .fa that could potentially create the problem.

**Comment by johnomics** [comment]
Thank for getting back to me - I only have the second run with 80269 dat files, matching the files in the ZIP file above. Here are the timestamps from this:
```
find . -name "*.dat" -printf '%t\t%p\n'| sort -n > ls_datfiles.txt
```

[ls_datfiles.txt.gz](https://github.com/CSB5/OPERA-MS/files/2758780/ls_datfiles.txt.gz)
