### ISSUE TITLE
Error in the short read mapping

### ISSUE THREAD

**Issue by SooyeongHwang** [CSB5/OPERA-MS#13]
Hi 

I am trying it on metagenomic data and I am having an issue in the short read mapping stage;

[log.err.txt](https://github.com/CSB5/OPERA-MS/files/2767120/log.err.txt)

and here is my config file;

'OUTPUT_DIR` /home/sooyeong/Data/PorecampData/OPERA-MS_out
CONTIGS_FILE /home/sooyeong/Data/PorecampData/NextSeq_evenStd/metaSPAdes_results/contigs.fasta
LONG_READ /home/sooyeong/Data/PorecampData/nanoporeData/raw_basecalled/all_reads_combined.fastq
ILLUMINA_READ_1 /home/sooyeong/Data/PorecampData/NextSeq_evenStd/nextSeq_1_PE.fastq 
ILLUMINA_READ_2 /home/sooyeong/Data/PorecampData/NextSeq_evenStd/nextSeq_2_PE.fastq 
LONG_READ_MAPPER minimap2
CONTIGS_FILE `/home/sooyeong/Data/PorecampData/OPERA-MS_out/intermediate_files/'

Could you help me to sole this, please?

Thanks

**Comment by dbertran78** [comment]
Hi SooyeongHwang,
it seems that your config file contains two `CONTIGS_FILE` flags and the last one point to a directory.
If you remove the following line from the config file it should work:
```CONTIGS_FILE/home/sooyeong/Data/PorecampData/OPERA-MS_out/intermediate_files/```

Regards.
