### ISSUE TITLE
Error in SIGMA execution.

### ISSUE THREAD

**Issue by SooyeongHwang** [CSB5/OPERA-MS#14]
Hi,

I have an issue during SIGMA execution.

Please help me out this issue.

I am attaching my config file and log files.

Thanks.
[err.tar.gz](https://github.com/CSB5/OPERA-MS/files/2826431/err.tar.gz)

**Comment by dbertran78** [comment]
Hi Sooyeong,
I am sorry for the delay.
It seems that the SIGMA configuration file was not generated correctly. I will need additional log files to identify your problem.
Could you please run the following commands, and share with me the `OPERA-MS-LOG.tar.gz` file.
``
opera_res=/home/sooyeong/Data/PorecampData/OPERA-MS//intermediate_files/
mkdir OPERA-MS-LOG/;
cp --parent $opera_res/*/*err* $opera_res/*/*out* $opera_res/strain_analysis/*/STRAIN*/log* $opera_res/strain_analysis/*/STRAIN*/opera.config OPERA-MS-LOG/; 
tar -cvzf OPERA-MS-LOG.tar.gz OPERA-MS-LOG/
``

Best regards,

--- Denis

**Comment by SooyeongHwang** [comment]
[OPERA-MS-LOG.tar.gz](https://github.com/CSB5/OPERA-MS/files/2929712/OPERA-MS-LOG.tar.gz)

Here are LOGs, I guess it didn't generate strain_analysis/.

Please check and let me know how to figure out this issue.

Thank you.

**Comment by dbertran78** [comment]
Can you share with me he config file that you use to run this test?

**Comment by SooyeongHwang** [comment]
This is my config file.



OUTPUT_DIR /home/sooyeong/Data/PorecampData/OPERA-MS/
LONG_READ /home/sooyeong/metagenome_porecamp/data/Nanopore/all_reads_combined.fastq
ILLUMINA_READ_1 /home/sooyeong/metagenome_porecamp/data/NextSeq/trimed_data/nextSeq_1_PE.fastq
ILLUMINA_READ_2 /home/sooyeong/metagenome_porecamp/data/NextSeq/trimed_data/nextSeq_2_PE.fastq
NUM_PROCESSOR 60


Thanks
________________________________

**Comment by valntn** [comment]
Hi Denis,

I have a similar issue. I ran the command you specified and attached the tar.gz here. It didn't generate strain_analysis/ for me either. On the provided sample data, it worked fine.

My config file:

#config file for opera_ms hybrid assembly
OUTPUT_DIR /home/u1797402/valentin/Metagenome/OPERA-MS_2
LONG_READ /home/u1797402/valentin/Metagenome/metagenome_flipflop.fastq
ILLUMINA_READ_1 /home/u1797402/valentin/Metagenome/shortreads/C204HW19040325/raw_data/MA_1/trimmed_reads/MA-1_trimmed_clean_decontaminated_1.fq.gz
ILLUMINA_READ_2 /home/u1797402/valentin/Metagenome/shortreads/C204HW19040325/raw_data/MA_1/trimmed_reads/MA-1_trimmed_clean_decontaminated_2.fq.gz
NUM_PROCESSOR 40
CONTIGS_FILE /home/u1797402/valentin/Metagenome/OPERA-MS/intermediate_files/megahit_assembly/final.contigs.fa

Best wishes,
Valentin

[OPERA-MS-LOG.tar.gz](https://github.com/CSB5/OPERA-MS/files/3186503/OPERA-MS-LOG.tar.gz)

**Comment by tpshea2** [comment]
Hello-
In the event the following info helps to troubleshoot this error, I encounter the same error at sigma stage:

> terminate called after throwing an instance of 'std::out_of_range'
>   what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 10)

Looking at the config files, and comparing to the config files posted elsewhere here on this issue, it looks like some of the optional parameters when not set are not getting the defaults passed along.

For instance the above user (sooyeong) has the following (showing only partial) sigma.config:

> output_dir=/home/sooyeong/Data/PorecampData/OPERA-MS//intermediate_files/coverage_estimation
> 
> edge_bundle_size_thr=2
> 
> kmer_size=
> 
> contig_len_thr=500
> 
> contig_edge_len=0
> 
> contig_window_len=0


and so maybe the fact that kmer_size, contig_edge_len, and contig_window_len are empty is causing (or contributing to) the fail?

In my coverage_estimation log.err file I see:

> Use of uninitialized value $kmer_size in concatenation (.) or string at /cil/shed/sandboxes/tshea/software/OPERA-MS/OPERA-MS/bin/runOperaMS.pl line 413.

My next step is to re-run from scratch and explicitly putting into the original starting config file the values for kmer_size, contig_edge_len, and contig_window_len.
