### ISSUE TITLE
Possibility to run with single end illumina reads

### ISSUE THREAD

**Issue by ilyavs** [CSB5/OPERA-MS#17]
Hello,
I know that the assembly with single ends results in lower performance. However, I have data of samples with long reads and single end illumina reads which I would like to use for assembly of ,metagenomes. Would it be possible to adjust the computational pipeline somehow to work with the single end data?
Thanks,
Ilya.

**Comment by dbertran78** [comment]
Hi,
As you mentioned using single ends reads may have a significant impact on the assembly performance especially if the read length is low (<50bp).
As it is, OPERA-MS can only be used with paired-end reads, and it will require some tweaking and testing  to integrate this new feature. Nevertheless, I think that it is a good idea to make OPERA-MS more flexible, and I will had this feature to the next release that should be out in around 2-3 weeks.

Best regards,

--- Denis

**Comment by ilyavs** [comment]
Hi,
Thank you very much!
Ilya.
