### ISSUE TITLE
Installation successful but failed on user provided dataset

### ISSUE THREAD

**Issue by arianccbasile** [CSB5/OPERA-MS#18]
Dear Denis,
We have installed the software both as a docker container and on a typical Linux/Unix system and on both the training set was successful. We are trying to run Opera-MS on our data. 

Using docker we get the following error: 
"my" variable $exe_check masks earlier declaration in same scope at OPERA-MS.pl line 444. Reading config file: /biofilm_docker.config Config file does not exist. Exiting.
We believe that the problem is related to the fact that our files are not in the container. 

Could you please provide a detailed procedure for moving the files to docker and run the program?

Using the other installation we have problems in running Racon with the following error:
./racon: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by ./racon)
We tried to install racon independently and we get another error related to the version of cmake but the installation of the required version was not successfully. 

Thank you in advance for your help.

Sincerely,
Arianna Basile

**Comment by lorenzgerber** [comment]
Hi Arianna,

Regarding the Docker issue: Could you share the `docker run` command with the specific args you used? Can you confirm that you executed the `docker run` command from within the base directory of the cloned operams git repository?

Cheers,
Lorenz
