### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Shirley-Q** [CSB5/OPERA-MS#21]
Hi，
There was an error when I install the OPERA-MS. I install capnm using commands 'sudo wget -c http://xrl.us/cpanm -O /usr/bin/cpanm sudo chmod +x /usr/bin/cpanm'
The error was as followed.
![WechatIMG3](https://user-images.githubusercontent.com/30583482/62606096-07ae2c00-b92e-11e9-886a-c9ff935b807e.jpeg)
![WechatIMG6](https://user-images.githubusercontent.com/30583482/62606125-1a286580-b92e-11e9-84cb-0619bf320315.jpeg)

**Comment by TongChengxuan** [comment]
Hi Shirley,

The following command can be used to install cpanm
curl -L https://cpanmin.us | perl - --sudo App::cpanminus

**Comment by Shirley-Q** [comment]
Thank you very much! But it didn't work.Could you help me?

**Comment by TongChengxuan** [comment]
Hi Shirley,
Can you show us your error message in a text file, you can send to our email at tong_chengxuan@gis.a-star.edu.sg and bertrandd@gis.a-star.edu.sg

**Comment by Shirley-Q** [comment]
Thanks very much！
![WechatIMG4](https://user-images.githubusercontent.com/30583482/62613318-d2a8d600-b93b-11e9-9c2a-fb42e8d0b54d.jpeg)

**Comment by TongChengxuan** [comment]
Hi Shirley,
can you do a ls -ld on /home/emma/.cpanm and show us the output.
if you do not have the write permission on the directory, you could change the permission and redo the installation
chmod u+w /home/emma/.cpanm

**Comment by Shirley-Q** [comment]
Hi,
I use the command 'chmod u+w /home/emma/.cpanm', but I still didn't have permission. I solved this problem for two days and I dont have any solution. Thank you very much! 
![1](https://user-images.githubusercontent.com/30583482/62668836-f877be80-b9bf-11e9-8afd-d15165ed0ae3.png)

**Comment by TongChengxuan** [comment]
Hi Shirley,

You can try 
chown emma /home/emma/.cpanm
then rerun the command.

if it still doesn't work, use the following command to download the executable directly to you home bin it should work.
cd ~/bin
curl -L https://cpanmin.us/ -o cpanm
chmod +x cpanm

**Comment by Shirley-Q** [comment]
Thanks very much! I run every command with 'sudo' and it worked.
