### ISSUE TITLE
Empty/malformatted entries in contigs.fasta

### ISSUE THREAD

**Issue by claczny** [CSB5/OPERA-MS#24]
Hi,

I am getting unexpected output in `contigs.fasta` (no `--polishing` option used).

Many of the lines look fine, but scrolling through the file, I find lines similar to the ones below appearing numerous times:
```
>opera_contig_1352 length: 43 cov_short: 11.68 cov_long: 5.59 cluster: NA
>opera_scaffold_1353 length: 16394 cov: 0.0
>
>opera_scaffold_1354 length: 16393 cov: 0.0
>
>opera_scaffold_1355 length: 16379 cov: 0.0
>
>opera_scaffold_1356 length: 16354 cov: 0.0
>
```

I became aware of this when running QUAST on the `contigs.fasta` and QUAST exited with an error.

Moreover, when I `grep`, e.g., for `opera_contig_1352` in `contig_info.txt`, I get
```
opera_contig_1352       43      11.68   5.59    NA      Eubacterium_cylindroides        NA      NC_021019.fna
```
When I `grep` for `opera_scaffold_1354`, there is no hit in `contig_info.txt`.

Any ideas where this might come from or what have I missed?

Thx!

Best,

Cedric

**Comment by dbertran78** [comment]
Hi Cedric
Let's first fix this error as it may be the cause of the error that you encounter during the polishing step.
Can you please run the following command (with the path to the OPERA-MS out-dir as an argument) to create a complete log files:
sh OPERA-MS/bin/get_log.sh path-to-opera-ms-out-dir
OPERA-MS-LOG.tar.gz will be create in your working directory.

Please send OPERA-MS-LOG.tar.gz, and the command line used for the OPERA-MS run to tong_chengxuan@gis.a-star.edu.sg and bertrandd@gis.a-star.edu.sg

Best regards,

--- Denis
 
PS: Sorry for the late reply, it was a quite long weekend in Singapore.

**Comment by claczny** [comment]
You have mail :)

Thank you for your help!

PS: No worries about the "late" reply as it is quick despite the "long weekend" 👍

**Comment by dbertran78** [comment]
Thank you for sharing the log file.
It helps me to identified a problem in the current version during the gapfilling procedure.
Please clone the latest version and try it on your dataset.

To avoid re-running the first steps you can delete the following directory:
``rm -r /mnt/lscratch/users/claczny/ont/fecal_pilot_testing/results/assembly/operams/lr_barcode07-sr_NEB2_MG_S17/intermediate_files/opera_long_read/``

And re-rerun the same OPERA-MS command line. The assembly will restart at stage 7 (Assembly of other clusters). The error should also solve the problem you encounter during polishing.

Best regards,

--- Denis

**Comment by claczny** [comment]
Thank you for fixing this so quickly.

I have rerun everything from the beginning and the run seems to have finished, but I am getting unexpected results.
Unexpected in the sense that the assembly statistics look poorer than the ones from the provided short-read contigs:

- OPERA-MS:
```
Number of contigs: 109760
Assembly size: 169961434 bp
Max contig size: 400978 bp
Contig(s) longer than 1Mbp: 0
Contig(s) longer than 500kbp: 0
Contig(s) longer than 100kbp: 86
Contig N50: 6135 bp
```

- MEGAHIT:
```
# contigs (>= 0 bp)         113369    
# contigs (>= 1000 bp)      29082
# contigs (>= 5000 bp)      6397
# contigs (>= 10000 bp)     3434
# contigs (>= 25000 bp)     1318
# contigs (>= 50000 bp)     538
N50 = 14412
L50 = 2379
Total length = 203929199
GC % = 46.96
# N's per 100 kbp =  0.00
Largest contig              652560
```
In particular the N50 and largest contig length struck me.

The MEGAHIT stats are from QUAST. However, I could not run QUAST on the `contigs.fasta` returned by OPERA-MS as I got an error from QUAST on that file.
I looked into it (as this error occured also prior to the fix) and, on first sight, could not find anything strikingly strange, except for maybe the last contig in the file:
```
>opera_contig_109760 length: -1 cov_short: 10.08 cov_long: 6.69 cluster: cluster_26
TGCTTCTTGAAGCAATCCGTACTTTGCCGGAAGAAAAGCGCAAAGCCATATTGCT ....
```
A length of "-1" appears strange to me.

Looking forward to your input.

Best,

Cedric

P.S. The ONT data used was not exceptionally large (~400k reads, 1.2Gbp) but I would still expect some improvements from it. Also, the fact that QUAST is failing puzzles me.

**Comment by claczny** [comment]
Found the likely source of the QUAST error:
There are again lines like
```
>strain14_opera_scaffold_264 length: 2078 cov: 0.0
>
>strain14_opera_scaffold_265 length: 2018 cov: 0.0
>
```
contained in the `contigs.fasta`. Not sure where the OPERA-MS error is though ;)

**Comment by dbertran78** [comment]
Seems that problem is not fully solved.
Could you please send me the new log files ?

Best regards,

--- Denis

**Comment by claczny** [comment]
Sure, you have mail.

Best,

Cedric

**Comment by dbertran78** [comment]
I had partially solved your problem in the previous version.
Please clone and try the latest version.

Regards,

--- Denis

**Comment by claczny** [comment]
Thank you, but still no valid `contigs.fasta`, e.g., 

```
>opera_contig_2166 length: 43 cov_short: 16.27 cov_long: 1.07 cluster: NA
>opera_scaffold_2167 length: 10534 cov: 0.0
>
>opera_scaffold_2168 length: 10534 cov: 0.0
>
```
While the assembly stats have changed to
```
[Wed Aug 14 12:48:17 2019]      Assembly stats
Number of contigs: 109772
Assembly size: 71306457 bp
Max contig size: 400978 bp
Contig(s) longer than 1Mbp: 0
Contig(s) longer than 500kbp: 0
Contig(s) longer than 100kbp: 79
Contig N50: 35901 bp
```

I now get the following message at the end of stdout:
```


ERROR: Did not find fasta records in "/mnt/lscratch/users/claczny/ont/testing/results/assembly/operams/lr-sr//opera_ms_clusters/cluster_10.fasta".

[...]

Illegal division by zero at /scratch/users/claczny/ont/apps/software/OPERA-MS//bin/cluster_info.pl line 224.


[Wed Aug 14 12:48:21 2019]      OPERA-MS completed
```

I will send you the logs again by email.

Best,

Cedric

**Comment by claczny** [comment]
@dbertran78 , thanks a lot for your help!
Commit 50a36ba fixes the errors for me and produces a valid `contigs.fasta` file.

For your info, the QUAST stats are below:
```
Assembly                    operams    megahit
# contigs (>= 0 bp)         109799     113369
# contigs (>= 1000 bp)      27670      29082
# contigs (>= 5000 bp)      6548       6397
# contigs (>= 10000 bp)     3540       3434
# contigs (>= 25000 bp)     1375       1318
# contigs (>= 50000 bp)     568        538
Total length (>= 0 bp)      224242547  222770320
Total length (>= 1000 bp)   183203483  180215077
Total length (>= 5000 bp)   141061851  135262960
Total length (>= 10000 bp)  120039887  114583407
Total length (>= 25000 bp)  86686319   81893413
Total length (>= 50000 bp)  58806303   55081684
# contigs                   59878      63448
Largest contig              652560     652560
Total length                205401426  203929199
GC (%)                      46.98      46.96
N50                         16429      14412
N75                         3076       2624
L50                         2172       2379
L75                         9887       11351
# N's per 100 kbp           0.02       0.00
```

While I could not observe the dramatic improvements reported in the paper, I attribute this to the relatively low amount of ONT data in our case.

I found OPERA-MS to be (rather) straight-forward to use (once the glitches were fixed ;) ) and also quick.

Thank you again for this piece of work!

Best,

Cedric
