### ISSUE TITLE
Errors during running cov_estimation

### ISSUE THREAD

**Issue by wangpeng407** [CSB5/OPERA-MS#26]
Thanks for your excellent tools of assembling.
If no --contig-file, it will assembling using megahit obtainning f**inal.contigs.fa**

Second step is read-mapping, generating contigs linked from ../opera.map.cov

Coming to third step, cov_estimation[cov_estimate.pl], the first sub script is cov_estimate.pl, when running this script, the error information in short_read_analysis.error is always "open: No such file or directory, [main_samview] fail to open opera.bam for reading."

The question is: 1) No such file, what file? 2) where is opera.bam[in cov_estimate.config file, it is LIB and MAPPING_FILES ], why not generated, which step generates this file?

Thanks a lot.

**Comment by dbertran78** [comment]
Dear wangpengnovos,
Can you please run the following command (with the path to the OPERA-MS out-dir as an argument) to create a complete log files:
``sh OPERA-MS/bin/get_log.sh path-to-opera-ms-out-dir``
OPERA-MS-LOG.tar.gz will be create in your working directory.

Please send OPERA-MS-LOG.tar.gz, and the command line used for the OPERA-MS run to tong_chengxuan@gis.a-star.edu.sg and bertrandd@gis.a-star.edu.sg

Best regards,

--- Denis

**Comment by wangpeng407** [comment]
Dear Denis,

Sincerely appreciate for your reply. This error has been solved just now. 

It is the version problem of ```usr/lib64/libstdc++.so.6``` when compiling ```short_read_analysis```. 

 So **updating ```gcc``` is the best way to solve this or likely problem**.

Thanks a lot.

**Comment by gazollavolpiano** [comment]
Hello! 

I am facing the same error wangpeng407 had.  

Any idea of how to overcome it?

I am using gcc  9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

Thank you very much!

**Comment by jsgounot** [comment]
Hi Camila,

as pointed before, this might be link to your gcc version. We're using gcc 7.5 (ubuntu 18.04) on our production server, I don't know if newer versions are an issue or not with OPERA-MS. I will check this for the next OMS version but I don't think I will be able to provide a quick fix for this with the current version. Meanwhile, you can install [alternative gcc versions](https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa) on your side. Please, let me know if this fix your issue. 

Regards,
Jean-Sebastien

**Comment by gazollavolpiano** [comment]
Dear Jean-Sebastien,

I tried gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 but the error continues.

Thank you for your help!

**Comment by jsgounot** [comment]
Dear Camila,

We have two options. First I suggest you to use the Docker image if you can, this could solve your problem very easily. Otherwise I will need the complete log to understand what is happening. Please follow instructions written by Denis on the same issue.

Regards,
Jean-Sebastien
