### ISSUE TITLE
Co-assemblies with multiple samples. 

### ISSUE THREAD

**Issue by kyakimovich** [CSB5/OPERA-MS#28]
Hello, 

I am planning a project to try and assemble some bacterial genomes from some environmental samples, and wanted to do some co-assemblies between multiple samples to more completely capture the core community. I was looking through the documentation, and couldn't find any mention if this was something OPERA-MS could do. 

Thanks! 
Kurt

**Comment by dbertran78** [comment]
Hi Kurt,
Yes – you can do the co-assembly and OPERA-MS should do something reasonable. We are also working on a version that keeps track of sample identities to improve co-assembly but currently you would just merge all read datasets.

Regards,

Denis
