### ISSUE TITLE
Running OPERA-MS step by step?

### ISSUE THREAD

**Issue by wangpeng407** [CSB5/OPERA-MS#29]
Hello,
      ```OPERA-MS``` mainly contains  9 steps in ```OPERA-MS.pl``` according to the sub-routines.
```
#step1
short_read_assembly(\%opera_ms_option, \%opera_ms_dependency);
#step 2
assembly_graph_creation(\%opera_ms_option, \%opera_ms_dependency);
#step 3
hierarchical_clustering(\%opera_ms_option, \%opera_ms_dependency);
#step 4
reference_clustering(\%opera_ms_option, \%opera_ms_dependency);
# step 5
strain_clustering_and_assembly(\%opera_ms_option, \%opera_ms_dependency);
# step 6
gap_filling(\%opera_ms_option, \%opera_ms_dependency);
# step 7
generate_assembly_stats(\%opera_ms_option, \%opera_ms_dependency);
#step 8
write_final_assembly(\%opera_ms_option, \%opera_ms_dependency);
# step 9
polishing(\%opera_ms_option, \%opera_ms_dependency);
```
The most important argument is ```%opera_ms_option```. After each step, script will rewrite or update it. So problem is that, if one step comes wrong, such as gap_filling or polishing, i have to running the program from the beginning. This is a time-consuming procedure.

Can we add an argument ```--step``` for ```OPERA-MS```? If so, we can jump some steps, and only  run the step which has errors.

**Comment by dbertran78** [comment]
Dear wangpengnovos,
Thank you very much for your comment.
I understand that it can be time consuming to restart a run from the beginning especially if one of the latest stage failed. This is why,  as stated in the readme, in case of a failure, if OPERA-MS is reran with the same command line, it will automatically detect stages that completed successfully and will skip them. For example if you wish to run the polishing stage on the test dataset (after running it without polishing), you can simply run: 
```
perl ../OPERA-MS.pl \
    --contig-file contigs.fasta \
    --short-read1 R1.fastq.gz \
    --short-read2 R2.fastq.gz \
    --long-read long_read.fastq \
    --polishing \
    --out-dir RESULTS 2> log.err
```
All the completed stages will be skipped and only the polishing stage will be run.

```
[Tue Aug 27 13:51:09 2019]	Short read assembly [1/9]
[Tue Aug 27 13:51:09 2019]	Skip [contig file provided as input]

[Tue Aug 27 13:51:09 2019]	Long-read mapping and assembly graph generation [2/9]
[Tue Aug 27 13:51:09 2019]	Stage previously completed

[Tue Aug 27 13:51:09 2019]	Short-read mapping and coverage estimation [3/9]
[Tue Aug 27 13:51:09 2019]	Stage previously completed

[Tue Aug 27 13:51:09 2019]	Hierarchical clustering [4/9]
[Tue Aug 27 13:51:09 2019]	Stage previously completed

[Tue Aug 27 13:51:09 2019]	Reference based clustering [5/9]
[Tue Aug 27 13:51:09 2019]	Stage previously completed

[Tue Aug 27 13:51:09 2019]	Strain clustering and assembly [6/9]
[Tue Aug 27 13:51:09 2019]	Stage previously completed

[Tue Aug 27 13:51:09 2019]	Assembly of other clusters [7/9]
[Tue Aug 27 13:51:09 2019]	Stage previously completed

[Tue Aug 27 13:51:09 2019]	Gap filling [8/9]
[Tue Aug 27 13:51:09 2019]	Stage previously completed
```

Best regards,

--- Denis
