### ISSUE TITLE
error during cov_estimate.pl

### ISSUE THREAD

**Issue by Shirley-Q** [CSB5/OPERA-MS#31]
Hi,
I run OPERA-MS with another data. There is an new error.

[nohup.txt](https://github.com/CSB5/OPERA-MS/files/3565417/nohup.txt)
Best,
Shirley

**Comment by dbertran78** [comment]
Hi Shirley,
Could you please send us the complete log file, that we could identify more precisely the error that happen on this data set.

Best regards,

--- Denis

**Comment by Shirley-Q** [comment]
[OPERA-MS-LOG.tar.gz](https://github.com/CSB5/OPERA-MS/files/3568127/OPERA-MS-LOG.tar.gz)

Thank you very much!
Best,
Shirley

**Comment by dbertran78** [comment]
Dear Shirley,
Thank you for sharing the log file.
As you may have seen in the log file file `/home/emma/QXJ/nanopore/AN2-284_pacbio_RESULTs/intermediate_files/coverage_estimation/cov_estimate.err` your reads are provided in an unrecognized format.
Looking at the command line you shared with us, I saw that your `.fq` files are compressed using the  `.tar.gz` format. Most of the bioinfomatic software does not support this format, and only support the `.gz` format. 
Please convert your sequencing files into `.gz` before running OPERA-MS.

Best regards,

--- Denis

**Comment by Shirley-Q** [comment]
Dear Denis,
I run the command successfully. Thanks!

Best,
Shirley
