### ISSUE TITLE
OPERA-MS running but gap filling frozen

### ISSUE THREAD

**Issue by dgmaghini** [CSB5/OPERA-MS#32]
Hi - running OPERA-MS on a large dataset (>25 gigabases of nanopore raw reads) and while it is still running, it has not updated any files that I can find in over a day. It seems that it is stuck somewhere in gap filling. Any ideas as to what is going on? 

[gap_filling.err](https://github.com/CSB5/OPERA-MS/files/3691400/gap_filling.err.txt)
[log.err](https://github.com/CSB5/OPERA-MS/files/3691402/log.err.txt)
[opera300919.out](https://github.com/CSB5/OPERA-MS/files/3691403/opera300919.out.txt)
[tilling_1_remap.out](https://github.com/CSB5/OPERA-MS/files/3691404/tilling_1_remap.out.txt)
[time.log](https://github.com/CSB5/OPERA-MS/files/3691405/time.log.txt)

**Comment by dbertran78** [comment]
Hi dgmaghini,
As stated on the time.log file, the gap-filling stage for your sample requires quite a lot of time. 
Looking at gap_filling.err, OPERA-MS is performing the last stage of the gap-filling: second round of contig mapping to the assembly which may require around 11h (similar time as the first round stated as g_tilling_1 in time.log).
During that stage, you should observe files written on the following directory:
`/labs/asbhatt/dmaghini/projects/southafrica/nanopore/C27/3.OPERA-MS//intermediate_files/opera_long_read/GAPFILLING/TILLING/mummer`

Were you able to complete the run during the weekend?
If not, could you please extract the complete log file `OPERA-MS-LOG.tar.gz` using the following command:
`/labs/asbhatt/dmaghini/tools/OPERA-MS//OPERA-LG/bin/get_log.sh /labs/asbhatt/dmaghini/projects/southafrica/nanopore/C27/3.OPERA-MS/`
And send OPERA-MS-LOG.tar.gz to me at bertrandd@gis.a-star.edu.sg 

We know that the gap-filling stage can be a time bottleneck for very large assemblies, and we are planning to improve its time performance in the upcoming releases.

Best regards,

--- Denis
