### ISSUE TITLE
Error in during gap_filling

### ISSUE THREAD

**Issue by lien27** [CSB5/OPERA-MS#35]
Hello,
I am having issues during contig remapping in gap filling and get the warning " /stor9000/apps/users/NWSUAF/2013130172/software/OPERA-MS-OPERA-MS-0.8.0//OPERA-LG/bin//Remap.py /stor9000/apps/users/NWSUAF/2013130172/rumen_microbes/singlecell/01.genomic/01.metawrap/01.pacbio/GTHC1/OPERA//intermediate_files/opera_long_read/GAPFILLING/TILLING/first_tilling.paf /stor9000/apps/users/NWSUAF/2013130172/rumen_microbes/singlecell/01.genomic/01.metawrap/01.pacbio/GTHC1/OPERA//intermediate_files/opera_long_read/GAPFILLING/TILLING/consensus.fa /stor9000/apps/users/NWSUAF/2013130172/rumen_microbes/singlecell/01.genomic/01.metawrap/01.pacbio/GTHC1/OPERA//intermediate_files/opera_long_read/GAPFILLING/TILLING/first_tilling_contig.fa > /stor9000/apps/users/NWSUAF/2013130172/rumen_microbes/singlecell/01.genomic/01.metawrap/01.pacbio/GTHC1/OPERA//intermediate_files/opera_long_read/GAPFILLING/TILLING/tilling_1_remap.out
Traceback (most recent call last):
  File "/stor9000/apps/users/NWSUAF/2013130172/software/OPERA-MS-OPERA-MS-0.8.0//OPERA-LG/bin//Remap.py", line 258, in <module>
    main(sys.argv[1:])
  File "/stor9000/apps/users/NWSUAF/2013130172/software/OPERA-MS-OPERA-MS-0.8.0//OPERA-LG/bin//Remap.py", line 225, in main
    final_assembly = get_final_assembly(initial_assembly, valid_contig_map_scaff, contig_seq, contig_start_sites, flag_extend_contig)
  File "/stor9000/apps/users/NWSUAF/2013130172/software/OPERA-MS-OPERA-MS-0.8.0//OPERA-LG/bin//Remap.py", line 164, in get_final_assembly
    insert_seq = contig_seq[next_contig_name]
KeyError: 'k141_3385707_length_2862_cov_927.1996_XXX_1' "
 What should I do? Thank you very much!

**Comment by TongChengxuan** [comment]
Hi,

Please run bin/get_log.sh  to get the complete error log and send it to tong_chengxuan@gis.a-star.edu.sg.
I observed you are using version 0.8.0, I would recommend you to download the latest version of OPERA-MS.

Regards
CX

**Comment by lien27** [comment]
Dear Dr. CX
  The complete error log have sended to your e-mail. It's strange that some sample data can be worked out using same script.
Regards
LZJ

**Comment by lien27** [comment]
Dear Dr. CX 
The  issue have been solved after updating the  version.
Regards
LZJ
