### ISSUE TITLE
Error messages when installed on readonly file system

### ISSUE THREAD

**Issue by stetner** [CSB5/OPERA-MS#36]
Version 0.8.3

All works well when I build it in my hoe directory and all tests succeed.

Move it onto a file system that is not world writable and get these errors when running:

    d.stetner 1815 $ perl /opt/Modules/opera-ms/0.8.3//OPERA-MS/OPERA-MS.pl CHECK_DEPENDENCY
    rm: cannot remove `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//perl': Read-only file system
    ln: creating symbolic link `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//perl': File exists
    *** OPERA-LG functional
    *** sigma functional
    *** samtools functional
    *** blasr functional
    *** bwa functional
    *** minimap2 functional
    *** mash functional
    
    mummer found in /opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23/ is not functional. Checking path for mummer.
    
    mummer found in path.
    
    mv /opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23//mummer /opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23//mummer.bk
    mv: cannot move `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23//mummer' to `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23//mummer.bk': Read-only file system
    
    
    ln -s /opt/Modules/opera-ms/0.8.3/OPERA-MS/utils/MUMmer3.23/mummer /opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23/
    ln: creating symbolic link `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23/mummer': Read-only file system
    
    *** mummer functional
    *** megahit functional
    *** spades functional
    *** racon functional
    *** pilon functional
    
    *** All compiled software are functional.
    *** Please try to run OPERA-MS on the test dataset.

Thanks for any suggestions.

**Comment by TongChengxuan** [comment]
Hi Stetner,
It seems you are installing in the root, unless you have root access. Alternatively, you could change the installation path to a non root directory, e.g. your home directory.

Best regards,
CX

**Comment by stetner** [comment]
Yes, you are correct CX.  I am installing it onto a computing cluster where many users may access it, but none of them should be able to change it.  I am assuming this is not a use case you planned for?  In that case I will need to have each user install it for themselves.

Thanks,
Doug

**Comment by TongChengxuan** [comment]
Hi stetner,
System admin or the root user can install OPERA-MS and other user can access it. Other users do not have to write on it.
Best regards,
CX

**Comment by stetner** [comment]
I have mounted the filesystem RW and see permission rather than read-only issues:

d.stetner 2161 $ sudo mount -o remount,rw /opt

d.stetner 2162 $ perl /opt/Modules/opera-ms/0.8.3//OPERA-MS/OPERA-MS.pl CHECK_DEPENDENCY
rm: cannot remove `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//perl': Permission denied
ln: creating symbolic link `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//perl': File exists
 *** OPERA-LG functional
 *** sigma functional
 *** samtools functional
 *** blasr functional
 *** bwa functional
 *** minimap2 functional
 *** mash functional

mummer found in /opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23/ is not functional. Checking path for mummer.

mummer found in path.

mv /opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23//mummer /opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23//mummer.bk
mv: cannot move `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23//mummer' to `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23//mummer.bk': Permission denied


ln -s /opt/Modules/MUMmer/3.23/mummer /opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23/
ln: creating symbolic link `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//MUMmer3.23/mummer': Permission denied

 *** mummer functional
 *** megahit functional
 *** spades functional
 *** racon functional
 *** pilon functional

 *** All compiled software are functional.
 *** Please try to run OPERA-MS on the test dataset.

**Comment by stetner** [comment]
Did a reinstall and now only get this 

$ perl /opt/Modules/opera-ms/0.8.3//OPERA-MS/OPERA-MS.pl CHECK_DEPENDENCY
rm: cannot remove `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//perl': Permission denied
ln: creating symbolic link `/opt/Modules/opera-ms/0.8.3/OPERA-MS//utils//perl': File exists
 *** OPERA-LG functional
 *** sigma functional
 *** samtools functional
 *** blasr functional
 *** bwa functional
 *** minimap2 functional
 *** mash functional
 *** mummer functional
 *** megahit functional
 *** spades functional
 *** racon functional
 *** pilon functional

 *** All compiled software are functional.
 *** Please try to run OPERA-MS on the test dataset.


And it seems to work on the test data.

**Comment by dbertran78** [comment]
This is great ! The installation completed successfully and should work on your own samples.
