### ISSUE TITLE
conda?

### ISSUE THREAD

**Issue by wwood** [CSB5/OPERA-MS#38]
Hi,

I'm on a somewhat odd setup where I cannot use cpanm, and make seems to fail as well. I think I've managed to cobble something together so it works, but it a little roundabout and hard for me to make available to others on my cluster. Would it be possible to submit a bioconda package or similar to help the install process?

Thanks, ben

**Comment by TongChengxuan** [comment]
Dear Ben,
 
OPERA-MS does not support a conda installation at the moment. However, it possible to create, in a few steps, a conda environment which wrap the perl modules dependency required by OPERA-MS.
Here  are the steps required to create the conda environment:
 
conda create -n OPERA-MS python 3.6
conda activate OPERA-MS
conda install -c bioconda perl-app-cpanminus
conda install -c r r-base
conda install -c anaconda gcc
export PERL5LIB=/path_to_conda/envs/OPERA-MS/lib/5.26.2:$PERL5LIB
 
As you can see, the last command requires you to indicate the full path to your conda environment, you should you executive the last line each time when you want to use OEPRA-MS, thus it is good to put it in a script as you conda activate OPERA-MS .
After that you can simply follow the OPERA-MS installation procedure.
Notice this is a one time installation process, for the following usages you will just have to activate the OPERA-MS environment using: conda activate OPERA-MS

We know that this not ideal, and we currently working on a more automated way to handle the perl library issues.

Please contact us if you meet any difficulties setting up the conda environment.
 
Best regards,
