### ISSUE TITLE
Error: "rm: cannot remove ‘*.sai’: No such file or directory" -

### ISSUE THREAD

**Issue by pkfsantos** [CSB5/OPERA-MS#4]
I am using OPERA-LG to scaffolding an Illumina genome assembled using pacbio data.
The program finished to run, but actually there is no change between the fasta file I use as input and the output fasta file.
The only "error" that I saw is: "rm: cannot remove ‘*.sai’: No such file or directory".
Follow are the output messages.

"
[...]
[bwa_aln_core] refine gapped alignments... 0.31 sec
[bwa_aln_core] print alignments... 0.43 sec
[bwa_aln_core] 563502918 sequences have been processed.
[main] Version: 0.7.17-r1188
[main] CMD: bwa samse -n 1 Tetrapedia_SOAPdenovo.fasta read.sai -
[main] Real time: 13206.938 sec; CPU: 6838.958 sec
[bam_sort_core] merging from 120 files...
PREPROCESS:
Fastq format is recognized
[Tue Aug 21 20:33:10 2018]	Building bwa index...
bwa index -p Tetrapedia_SOAPdenovo.fasta /scratch/8172532/Tetrapedia_SOAPdenovo.fasta
[Tue Aug 21 20:41:00 2018]	Finding the SA coordinates of the reads using BWA aln...
[Wed Aug 22 19:19:16 2018]	Generate alignments of reads using bwa sampe...
bwa samse -n 1 Tetrapedia_SOAPdenovo.fasta read.sai - | grep '\(^@\|XT:A:U\)' | samtools view -S -h -b -F 0x4 - | samtools sort -@ 20 -no - temporarySam > SOAP-opera2.bam
[Wed Aug 22 23:16:10 2018]	Preprocessing done!
Mapping long-reads using blasr...
/scratch/apps/blasrbinary/blasr  -nproc 1 -m 1 -minMatch 5 -bestn 10 -noSplitSubreads -advanceExactMatches 1 -nCandidates 1 -maxAnchorsPerPosition 1 -sdpTupleSize 7 /scratch/8172532/All_pacbio_SMRT.fasta /scratch/8172532/Tetrapedia_SOAPdenovo.fasta | cut -d ' ' -f1-5,7-12 | sed 's/ /\t/g' > SOAP-opera2.map
Sorting mapping results...
sort -k1,1 -k9,9g  SOAP-opera2.map > SOAP-opera2.map.sort
N50: 127830250
i1	300	1000
i3	2000	5000
i5	15000	40000
i0	-200	300
i2	1000	2000
i4	5000	15000
Analyzing sorted results...
Extracting linking information...
Repeat detection...
/scratch/apps/OPERA-LG_v2.0.6/bin//filter_conflicting_edge.pl pairedEdges_i0 contig_length.dat 100 2

 *** 344  edges filtered from 1440 (0.238888888888889)

rm anchor_contig_info.dat contig_length.dat filtered_edges.dat filtered_edges_cov.dat *.sai
rm: cannot remove ‘*.sai’: No such file or directory
mv SOAP-opera2.bam SOAP-opera2-with-repeat.bam
/scratch/apps/OPERA-LG_v2.0.6/bin//filter_repeat.pl SOAP-opera2-with-repeat.bam repeat.dat | samtools view - -h -S -b > SOAP-opera2.bam
[samopen] SAM header is present: 15508 sequences.
rm SOAP-opera2-with-repeat.bam
/scratch/apps/OPERA-LG_v2.0.6/bin/OPERA-LG config > log
Analyzing 1 library: SOAP-opera2.bam
min library mean : 250
minimum contig length is 500
Current library: 1 out of 7
Analyzing file: pairedEdges_no_repeat_i0
Analyzing file: pairedEdges_no_repeat_i1
Analyzing file: pairedEdges_no_repeat_i2
Analyzing file: pairedEdges_no_repeat_i3
Analyzing file: pairedEdges_no_repeat_i4
Analyzing file: pairedEdges_no_repeat_i5
ln -s results/scaffoldSeq.fasta scaffoldSeq.fasta"

Could someone help me? What is wrong?
Priscila

**Comment by dbertran78** [comment]
Can you give me the command line that you used to run the program ?
By the way, your on the OPERA-MS page and not the OPERA-LG one.

**Comment by pkfsantos** [comment]
Thank you for your answer. You are right, I have to make a post in their sourceforge page.
Anyway, If you have some idea, my command line was:

OPERA-long-read.pl --blasr /apps/blasrbinary --opera /apps/OPERA-LG_v2.0.6/bin --contig-file contig.fasta --kmer 63 --illumina-read1 /scratch/8172532/All_reads_1.fastq --illumina-read2 /scratch/8172532/All_reads_2.fastq --long-read-file All_pacbio_SMRT.fasta --output-prefix SOAP-opera2 --output-directory SOAP-opera2
