### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by msevi** [CSB5/OPERA-MS#43]
Hi I'm trying to run OPERA-MS in a compute cluster that has time limitations. In the description I came across this: "Note that in the case of interruption during an OPERA-MS run, using the same command-line will re-start the execution after the last completed checkpoint." 

I'm curious about what the checkpoints are.

The assembly step is time consuming and timed out, I re-ran the OPERA-MS command thinking it would pick up where it left off, but it started fresh. I know that megahit has a --continue flag, but this argument does't show up in the OPERA-MS.pl --help. How can I incorporate that flag?

Thanks

**Comment by dbertran78** [comment]
Dear msvi,
OPERA-MS checkpoints are the steps indicated on your log output file (e.g., **Short read assembly**, **Long-read mapping and assembly graph generation**, and so on).
In your particular case, you are referring to the **Short read assembly** step, and OPERA-MS will re-start the complete assembly.
To avoid re-starting the contig assembly from scratch,  you could manually run the MEGAHIT assembly using the parameters provided in **out_dir/intermediate_files/megahit_assembly/opts.txt** and add the extra **--continue** flag.
Finally, you can restart OPERA-MS by providing the path to your assembled contigs using the option **--contig-file**. 

Best regards,

--- Denis

**Comment by msevi** [comment]
Thank you. I will give it a try this way.

Cheers,
Maria

**Comment by msevi** [comment]
Hi Denis, 
I re ran following your recommendation and the program completed without apparent error, returning the following in the results folder:
> assembly.stats    
> contig_info.txt  
> intermediate_files  
> opera-ms.config
> cluster_info.txt  
> contigs.fasta    
> opera_ms_clusters

However, when I run the same script for a different data set, it fails on the following step
> Reference based clustering [5/8]

Looking at the log output files and github issues for OPERA-MS, it leads me to believe it's a nucmer related issue. In fact, when I check dependencies, it exits on nucmer:
`perl ./OPERA-MS/OPERA-MS.pl CHECK_DEPENDENCY`

> *** OPERA-LG functional
>  *** sigma functional
>  *** samtools functional
>  *** blasr functional
>  *** bwa functional
>  *** minimap2 functional
>  *** mash functional
> 
> mummer found in /scratch/m.sevi/processing/WW_HRSD/03_hybrid_assembly/OPERA-MS//utils//MUMmer3.23/ is not functional. Checking path for mummer.
> mummer not found in path. Exiting.

**I'm confused as to why**, because when I installed the program my output for 
`perl ./OPERA-MS/OPERA-MS.pl CHECK_DEPENDENCY` was the following:

> *** OPERA-LG functional 
> *** sigma functional 
> *** samtools functional 
> *** blasr functional
> *** bwa functional 
> *** minimap2 functional 
> *** mash functional 
> *** mummer functional 
> *** megahit functional 
> *** spades functional 
> *** racon functional 
> *** pilon functional 
> 
> *** All compiled software are functional.
> *** Please try to run OPERA-MS on the test dataset.

And running OPERA-MS on the test dataset and on my own data, worked fine initially. 
Do you have any insight about my issue? Any additional info I can provide to troubleshoot it?

Thanks,
Maria

**Comment by dbertran78** [comment]
Dear Maria,
It seems that MUMmer is not functional on your system anymore.
Probably some C/C++ libraries got changed/updated in between you run.
Perhaps re-installing MUMmer in the current state of your machine/server may fix the problem or at least indicate you which libraries are missing:
```
#In the OPERA-MS instalation directory
cd utils
rm -r MUMmer3.23/ 
sh install_mummer3.23.sh
```
Best regards,

--- Denis

**Comment by msevi** [comment]
Hi Denis,
Thank you!  Followed your advice. All dependencies are now functional. 
Best,
Maria
