### ISSUE TITLE
Missing dependency - R

### ISSUE THREAD

**Issue by susheelbhanu** [CSB5/OPERA-MS#44]
Hey all, 

Thanks for putting together this tool. I was trying to run the `test_files` and found that `R` is a dependency which is not mentioned in the original documentation. 

The run was stopped at `Strain clustering and assembly [6/8]`. After installing `r-base` in my conda environment, it seemed to have restarted again. 

Best,
Susheel

**Comment by TongChengxuan** [comment]
Hi Susheel,

Thanks for letting us know, we have update the readme page.

Best regards,
Chengxuan
