### ISSUE TITLE
Error in `generate_assembly_stats.pl` ?

### ISSUE THREAD

**Issue by susheelbhanu** [CSB5/OPERA-MS#45]
Hey there, 
I'm using OPERA-MS to build hybrid assemblies, and got an error in the final step, i.e. `generate assembly stats`. 

When looking in to the error, the message said that there was an issue with the `generate_assembly_stats.pl` file. Looking closer, the said file starts as shown below:

```
2#use strict;
use warnings;
use Statistics::Basic qw(:all);
```

Is this a typo? I noticed that the other `.pl` files in the `utils` folder start with the following:
```
#!/usr/bin/perl
#use strict;
```

Could you please clarify so I can make the necessary change? Thank you!

**Comment by TongChengxuan** [comment]
Hi,

We have edit the code, sorry for the inconvenient caused. Please pull the code or remove the "2" for the first line.

Best regards,
Chengxuan

**Comment by susheelbhanu** [comment]
Thank @TongChengxuan. Will let you know if it fixes the issue.
