### ISSUE TITLE
extract_read_sequence.pl keeps running endless

### ISSUE THREAD

**Issue by dawnmy** [CSB5/OPERA-MS#47]
I am running the assembler (v0.8.3) on a pooled dataset (10 samples) with 160M short reads and 16M long reads in total. After it finished the step `Gap filling [8/8]`, `extract_read_sequence.pl` keeps running for already 4 days without any output. The process status of `extract_read_sequence.pl` is `D`. Tracing the process with `strace` shows :

```
open("results/assembly/operams_pooled/sample_pooled//intermediate_files/opera_long_read/GAPFILLING/strain97_opera_scaffold_9/POOL.fastq", O_WRONLY|O_CREAT|O_APPEND, 0666) = 6
lseek(6, 0, SEEK_END)                   = 3328329
ioctl(6, TCGETS, 0x7ffd25cf24a0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(6, 0, SEEK_CUR)                   = 3328329
fstat(6, {st_mode=S_IFREG|0644, st_size=3328329, ...}) = 0
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0
write(6, "@S8R1408983\nAATTTGACATCTTTATTGTT"..., 6744) = 6744
close(6)
```
Is there a way to get out of it?

**Comment by TongChengxuan** [comment]
Hi,

Does the output been produced? is there a assembly_stat file in the output folder? It is hard to determine what caused the above process. Appreciate if you can advise more details like if there is any error and etc.

Best regards,
Chengxuan

**Comment by dawnmy** [comment]
Finally it produced the contig file after running for a week. I think it is just because the dataset is too large.
