### ISSUE TITLE
no contigs.fasta output, problem with Gap filling step

### ISSUE THREAD

**Issue by DDavila10** [CSB5/OPERA-MS#56]
Hi all,

I am currently using OPERA-MS. I run the test files and works perfectly but using my data I do not have a final contings.fasta, conting_info.txt or assembly.stats. 

The log.err indicates a problem in Gap_filling step

/beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/..//tools_opera_ms/perl /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/..//OPERA-LG/bin//gapfilling.pl /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/opera_long_read/GAPFILLING /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/megahit_assembly/final.contigs.fa /beegfs/group_dv/home/DDavila/mouse_metagenomes/adaptor_trimmed_mouse0476_metagenomics_nanopore.fa /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/read_mapping 10 499 /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/..//OPERA-LG/bin/ /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/..//tools_opera_ms/ /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/..//tools_opera_ms/ /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/..//tools_opera_ms/ /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/..//tools_opera_ms//MUMmer3.23/ 2> /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/opera_long_read/GAPFILLING/gap_filling.err

and the last step of OPERA-MS only mentioned

[Mon Apr  5 18:36:03 2021]      Gap filling [8/8]

and then stops

Could you please help me with this problem? I would really appreciate it !

Best,

**Comment by jsgounot** [comment]
Hi Davila,

Thanks for using OPERA-MS ! Is `/beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/opera_long_read/GAPFILLING/gap_filling.err` empty ?

**Comment by DDavila10** [comment]
Hi Jean-Sebastien,

Thank you so much for your prompt reply. gap_filling.err is not empty

/beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/..//tools_opera_ms//perl /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/..//OPERA-LG/bin//extract_read_sequence.pl --edge-file /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/read_mapping/edge_read_info.dat --contig-file /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/megahit_assembly/final.contigs.fa --opera-lr-dir /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/opera_long_read/GAPFILLING/../ --read-file /beegfs/group_dv/home/DDavila/mouse_metagenomes/adaptor_trimmed_mouse0476_metagenomics_nanopore.fa --output-directory /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/opera_long_read/GAPFILLING 2> /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/opera_long_read/GAPFILLING/extract_read.err

but tilling_1.err is empty 

Could you please help me to solve this problem?

Thanks a lot in advance

Best,

**Comment by DDavila10** [comment]
extract_read.err contains:

*** Starting the sequence extraction
rm -rf /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/opera_long_read/GAPFILLING/LOG
mkdir -p /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/opera_long_read/GAPFILLING/LOG
 *** Number of edges selected for gapfilling 119896
 /beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/opera_long_read/GAPFILLING/contig_extention.log
 *** Extract gap sequences from read file /beegfs/group_dv/home/DDavila/mouse_metagenomes/adaptor_trimmed_mouse0476_metagenomics_nanopore.fa

Is it helpful for you?

Best,

**Comment by jsgounot** [comment]
Did you mean `extract_read.err` instead of `tilling_1.err` ? If not, is it also empty ?

Regards,

**Comment by jsgounot** [comment]
That's unusual, in this context your file `/beegfs/group_dv/home/DDavila/mouse_metagenomes/adaptor_trimmed_mouse0476_metagenomics_nanopore.fa` is supposed to contained reads. Is this the case ? Can you share the command line you used to run OPERA-MS ?

**Comment by DDavila10** [comment]
Thanks for the prompt answer! sorry for the misunderstanding. 

extract_read.err is not empty 
tilling_1.err is empty. 

/beegfs/group_dv/home/DDavila/mouse_metagenomes/adaptor_trimmed_mouse0476_metagenomics_nanopore.fa contains all the nanopore sequences. 

This is the script that I used for running OPERA-MS

#!/bin/bash
#SBATCH --cpus-per-task=18
#SBATCH --mem=15gb
#SBATCH --time=5-24 
#SBATCH -p hooli
#SBATCH -o mouse1.kneaddata.opera.assembly.out

singularity exec /beegfs/common/singularity/bioinformatics_software.v3.0.7.sif /bin/bash << SHI

#!/bin/bash
source ~/.bashrc

module load perl

perl ../OPERA-MS.pl \
    --short-read1 all_paired1_kneaddata_mouse0476.fastq \
    --short-read2 all_paired1_kneaddata_mouse0476.fastq \
    --long-read ~/mouse_metagenomes/adaptor_trimmed_mouse0476_metagenomics_nanopore.fa \
    --no-ref-clustering \
    --out-dir hybrid_reference_metagenome_by_opera_mouse0476 2> log.err

In our server, we use images and Singularity. I used the same script for the test_files and works perfectly.

Best,

**Comment by jsgounot** [comment]
Could you also looked the content of this file ? `/beegfs/group_dv/home/DDavila/OPERA-MS/opera_assembly_reference_metagenome/hybrid_reference_metagenome_by_opera_mouse0476//intermediate_files/opera_long_read/GAPFILLING/edge_err`

thanks,

**Comment by DDavila10** [comment]
yes, the content looks like

k99_1575792-vs-k99_92999        01c989c7-2f88-42f1-96f9-dfd2fdfe4c15    NA              2758    2659    99      OVERLAP
k99_551112-vs-k99_587244        3068709b-66e0-4867-a8d8-dede2ccd07f7    NA              980     880     100     OVERLAP
k99_512847-vs-k99_731839        6acedaa1-9025-4a0e-b73f-8476167c5337    0       1518    1985    467     GAP
k99_1788660-vs-k99_185894       4a415099-186b-4737-9dc1-048e91878a0c    NA              588     576     12      OVERLAP
k99_1136312-vs-k99_1338282      546970f7-6a4e-4968-82af-0575606149e0    0       10945   11166   221     GAP
k99_266455-vs-k99_680457        1a37ee91-3e6e-4273-9bfd-8c95b77ab60e    0       10659   12551   1892    GAP
k99_1002566-vs-k99_2081854      0ac42566-d74e-423b-9621-6d78618bf8c6    NA              4931    4834    97      OVERLAP
k99_1244537-vs-k99_669254       0ac42566-d74e-423b-9621-6d78618bf8c6    NA              3418    3329    89      OVERLAP
k99_2081854-vs-k99_669254       0ac42566-d74e-423b-9621-6d78618bf8c6    NA              4356    4257    99      OVERLAP
k99_2104342-vs-k99_836226       0ac42566-d74e-423b-9621-6d78618bf8c6    NA              646     544     102     OVERLAP
k99_1244537-vs-k99_2104342      0ac42566-d74e-423b-9621-6d78618bf8c6    NA              2491    2390    101     OVERLAP
k99_2101708-vs-k99_399170       d926bedb-70ba-430b-b027-2d2742df5494    NA              4841    4743    98      OVERLAP
k99_1607702-vs-k99_956367       9f9b6b18-d96f-4a48-b914-dc75dd8ec8f9    NA              2465    2372    93      OVERLAP
k99_1781482-vs-k99_2431936      15e106a1-da3f-4d9e-9f81-3d6477ce3b01    1       1418    2269    851     GAP
k99_2431936-vs-k99_933394       15e106a1-da3f-4d9e-9f81-3d6477ce3b01    1       3176    10297   7121    GAP
k99_1578627-vs-k99_1670263      0c9256b6-1998-4d56-ae33-10efbd033e7c    NA              6834    6736    98      OVERLAP
k99_1578627-vs-k99_5172 0c9256b6-1998-4d56-ae33-10efbd033e7c    NA              10680   10584   96      OVERLAP
k99_119743-vs-k99_2204764       09971716-1c0e-435e-95f3-c0ab1a25175c    NA              1050    948     102     OVERLAP
k99_1343127-vs-k99_786594       07aea4a4-00ea-421f-8fbf-2427e596218b    NA              759     661     98      OVERLAP
k99_1732075-vs-k99_906783       c9dc1130-b543-4132-bdb0-eb4e9d68c3aa    1       8065    8795    730     GAP
k99_457650-vs-k99_734317        2552358d-b184-4a97-b98d-b213ee967981    NA              10244   10148   96      OVERLAP
k99_404361-vs-k99_874010        2552358d-b184-4a97-b98d-b213ee967981    NA              5467    5368    99      OVERLAP
k99_2019235-vs-k99_874010       2552358d-b184-4a97-b98d-b213ee967981    0       7031    7275    244     GAP
k99_2019235-vs-k99_734317       2552358d-b184-4a97-b98d-b213ee967981    0       8940    8983    43      GAP
k99_138485-vs-k99_748446        2552358d-b184-4a97-b98d-b213ee967981    0       15247   15912   665     GAP

Best,

**Comment by jsgounot** [comment]
Ok then it's really weird and I will be unable to debug this without your input files. Is it possible for you to mail them to me ? Sorry for inconvenience.

**Comment by DDavila10** [comment]
thanks for the valuable help. I can share part of the input files. Where should I send it to?

**Comment by jsgounot** [comment]
jsgounot+github@gmail.com

**Comment by DDavila10** [comment]
Hi Jean-Sebastien,

After checking, I had a problem with the nanopore.fa file, so I used the fastq version of the same reads and works!! Thanks a lot for the valuable help, support and prompt response!

Best!
