### ISSUE TITLE
Update megahit

### ISSUE THREAD

**Issue by Unaimend** [CSB5/OPERA-MS#61]
Do you think it would make sense to update the version of megahit?

**Comment by jsgounot** [comment]
Yes and this should be naturally resolved in the long-term global enhancement project where OMS is fully integrating into a specific conda environment (without local tools installations). 

Meanwhile, a trick could be to simply replace the local executable to a more recent one. I will check later but the output is most likely the same between the two versions (OMS : 1.0.4, latest is 1.2.9).

**Comment by Unaimend** [comment]
Integrating OMS into conda sounds like a really good idea. And yeah I have to admit it did not check the releases of megahit for a changelog, but I presume they would not increase their version number if they would not have changed anythinkg. 
Thanks for your work

**Comment by Unaimend** [comment]
So I just a quick look at megahit, and they seem to have fixed quite a few bugs since 1.04

**Comment by jsgounot** [comment]
I just try with MEGAHIT v. 1.2.9 and did not encounter any issue with my test data. You can simply remove the megahit executable in the tools_opera_ms directory and replace it with a softlink to your conda / latest MegaHit executable.
