### ISSUE TITLE
Make a lot more short read assembly parameter configurable from the opera command line

### ISSUE THREAD

**Issue by Unaimend** [CSB5/OPERA-MS#62]
A lot of important parameters for spades and megahit have to be configured in the perl script which seems a little bit annoying.
I think it would make sense to expose those to the opera command line. If you agree I could submit a pull request.

**Comment by jsgounot** [comment]
Hi,

this could be a good idea indeed. For reference, Megahit calling is [here](https://github.com/CSB5/OPERA-MS/blob/31544de943e3996713faaffa528410222476f93d/OPERA-MS.pl#L500) and Spades calling is [here](https://github.com/CSB5/OPERA-MS/blob/31544de943e3996713faaffa528410222476f93d/OPERA-MS.pl#L521).

* Megahit is used with default parameters + threading option (`-1 fq1 -2 fq1 -o outfile --num-cpu-threads n`)
* Spades is used with more options (`-1 fq1 --2 fq2 --k 21,33,55,81 -o outdir --meta --threads n`)

Maybe only the Spades kmer size is revelant to be exposed to the OMS command line. What do you think ?

Regards,
jsgounot

**Comment by Unaimend** [comment]
I would have to look into it but I've heard somewhere that, for example, a trick to reduce the memory consumption of megahit is to increase the k-mer-min from 21 to a higher number. Over the course of the last 4 days, I tried to start megahit with different arguments because my assembly of a metagenome( ~350GB of reads) died on me every time. But when I edited the OMS perl script, for some reason the arguments were not passed to megahit.

Regards
Thomas Dost

**Comment by jsgounot** [comment]
Ok, this is odd because I just checked and I'm able to edit MegaHit command line by editing the OPERA-MS.pl file, for example :

```
run_exe($opera_ms_dependency->{"megahit"}."/megahit " . 
  "--num-cpu-threads " . $opera_ms_option->{"NUM_PROCESSOR"} . " " .
  "--k-max 151 " .
  "-1 " . $opera_ms_option->{"ILLUMINA_READ_1"} . " " .
  "-2 " . $opera_ms_option->{"ILLUMINA_READ_2"} . " " .
  "-o " . $megahit_out_dir . "> $inter_dir/megahit.out 2> $inter_dir/megahit.err");
```

Which options are you trying to add ?
