### ISSUE TITLE
Multiple Short Reads

### ISSUE THREAD

**Issue by iek** [CSB5/OPERA-MS#69]
Does OPERA-MS work on multiple short reads (not just one pair of short reads)?

**Comment by jsgounot** [comment]
Hi,

no sorry, the only way is to [concatenate the reads](https://www.biostars.org/p/9469504/).

Regards,
jsgounot

**Comment by iek** [comment]
Thank you for your quick reply! Based on the link you sent, does that mean I should interleave my reads? I have several pairs of paired end short reads, so I wasn't sure how to concatenate them properly into two files. Thank you again.

**Comment by jsgounot** [comment]
Hi. No, you should not interleave your reads. You just need to be careful of the concatenation order which must be the same for the two output files.

**Comment by iek** [comment]
Thank you!
