### ISSUE TITLE
test successful but failed running on my dataset

### ISSUE THREAD

**Issue by Dong-Ning** [CSB5/OPERA-MS#7]
Hi!

OPERA-MS was successfully installed on my server since it passed the test. However, an error occurred when I ran my own data. Here is the message: 

Error in during strain clustering assembly. Please see /work/install/OPERA-MS/YLW_output_all//intermediate_files/strain_analysis/assembly.cmd.log for details.

I did not get any clue from the  assembly.cmd.log file. Could you please help me?
Here are the last few lines of the file:
*** Add contig k99_901825 -> k99_901825
 *** Add contig k99_901867 -> k99_901867
 *** Add contig k99_901896 -> k99_901896
 *** Add contig k99_901898 -> k99_901898
Analyzing file: /work/install/OPERA-MS/YLW_output_20181111//intermediate_files/strain_analysis/Roseburia_intestinalis/STRAIN_2/pairedEdges_i0/pairedEdges_i0
Analyzing file: /work/install/OPERA-MS/YLW_output_20181111//intermediate_files/strain_analysis/Roseburia_intestinalis/STRAIN_2/pairedEdges_i1/pairedEdges_i1
Analyzing file: /work/install/OPERA-MS/YLW_output_20181111//intermediate_files/strain_analysis/Roseburia_intestinalis/STRAIN_2/pairedEdges_i2/pairedEdges_i2
Analyzing file: /work/install/OPERA-### MS/YLW_output_20181111//intermediate_files/strain_analysis/Roseburia_intestinalis/STRAIN_2/pairedEdges_i3/pairedEdges_i3
Analyzing file: /work/install/OPERA-MS/YLW_output_20181111//intermediate_files/strain_analysis/Roseburia_intestinalis/STRAIN_2/pairedEdges_i4/pairedEdges_i4
Analyzing file: /work/install/OPERA-MS/YLW_output_20181111//intermediate_files/strain_analysis/Roseburia_intestinalis/STRAIN_2/pairedEdges_i5/pairedEdges_i5

Many thanks,
Ning

**Comment by dbertran78** [comment]
Dear Ning, thank you for your interest on OPERA-MS.
I will you the detailed logs to identify the problem.
Could you please run the following command line:
opera_res=/work/install/OPERA-MS/YLW_output_20181111//intermediate_files/
mkdir OPERA-MS-LOG/;cp --parent $opera_res/*/*err*  $opera_res/*/*out*  $opera_res/strain_analysis/*/STRAIN*/log*  $opera_res/strain_analysis/*/STRAIN*/opera.config OPERA-MS-LOG/; tar -cvzf  OPERA-MS-LOG.tar.gz  OPERA-MS-LOG/   

You can send me the OPERA-MS-LOG.tar.gz file to dbertran78@gmail.com

Thank you

Denis

**Comment by Dong-Ning** [comment]
Thanks Denis,

I have sent the file to you 2 days ago. I look forward to your reply.

Best,
Ning

**Comment by dbertran78** [comment]
I am sorry, but I did not see your email.
Can you indicate me what was the subject, or even re-send me the file.

**Comment by Dong-Ning** [comment]
The subject is "OPERA-MS test successful but failed running on my dataset". I will resend the email. The message was sent with my university email. You can also check your junk email. Thanks.

**Comment by Dong-Ning** [comment]
Hi Denis,

The NEW VERSION works well on my computer. Many thanks.

Ning
