### ISSUE TITLE
GAPFILLING - Nucmer error

### ISSUE THREAD

**Issue by drelo** [CSB5/OPERA-MS#72]
After fixing some issues referred here #71  I run into another error
I installed operams like this

```
mamba create -n andresOperams
mamba activate andresOperams
mamba install -n andresOperams -c compbiocore perl-switch perl==5.26.2
mamba install -n andresOperams -c bioconda perl-file-which perl-statistics-basic perl-statistics-r
mamba install perl-app-cpanminus

```
I added the trick of linking Perl into tools folder `ln -s $(which perl) tools_opera_ms/perl`
After this I got an error regarding samtools, so I installed every dependency in this newly created environment 

`mamba install -c bioconda megahit spades samtools bwa blasr minimap2 racon mash mummer pilon  ncurses`

I replaced the samtools inside the tools_opera_ms folder with the one from conda like this  `which samtools | awk '{ print "ln -s "$0" ."}'  | bash`

Then I run the test data but it failed in the 8th step

> rm -r /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/QUERY /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/REF
> rm: no se puede borrar '/mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/QUERY': No existe el fichero o el directorio
> rm: no se puede borrar '/mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/REF': No existe el fichero o el directorio
> mkdir /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/REF
>  *** split /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/consensus.fa
> mkdir /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/QUERY
>  *** split /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/user_assembly/contigs.fasta
>  *** run the mummer mapping
> rm -r /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/mummer
> rm: no se puede borrar '/mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/mummer': No existe el fichero o el directorio
> mkdir /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/mummer
> cat /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/mummer/cmd_delta.txt | xargs -I cmd --max-procs=2 bash -c cmd > /dev/null
> 
> Error in during nucmer.

[Here is the conda environment ](https://github.com/CSB5/OPERA-MS/files/8201138/opera.txt)

[Here are the three](https://github.com/CSB5/OPERA-MS/files/8201168/tilling_1.err.txt) [ log files involved](https://github.com/CSB5/OPERA-MS/files/8201169/gap_filling.err.txt) [ in the error](https://github.com/CSB5/OPERA-MS/files/8201170/log.err.txt)

Let me know If I can provide more log or details

Thanks for your help

> R version 3.5.1 (2018-07-02) -- "Feather Spray"
> Statistics::R
> -------------------------------------------------------------------------
> 	(no description)
> 	F/FA/FANGLY/Statistics-R-0.34.tar.gz
> 	/home/corongoyo/.local/miniconda/envs/andresOperams/lib/site_perl/5.26.2/Statistics/R.pm
> 	Installed: 0.34
> 	CPAN:      0.34  up to date
> 	Florent Angly (FANGLY)
> 	CENSORED
> 
> Perl is installed at ~/.local/miniconda/envs/andresOperams/bin/perl
> This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

**Comment by jsgounot** [comment]
Hi @drelo, I'm very sorry to see you hit another error. This sounds very similar to issue #63 but not exactly in the same workflow location. 

There are two points here:
1. Could you share the error linked to samtools? I do not recommend to replace softwares, this could lead to unknown incompatibility with OPERA-MS workflow. 
2. Could you please share the file `/mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/mummer/cmd_delta.txt`? Also, can you pick one of the command inside this file and try to run it alone to see what exactly the error is?

Thank you very much,
JS

**Comment by drelo** [comment]
Thanks again for your help here are more details...

### 1) 
First I got this error in the log.err file

```
Error in during cov_estimate.pl. Please see /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/coverage_estimation/cov_estimate.out and /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/coverage_estimation/cov_estimate.err for details.
```
The cov_estimate.err in turn gives this at the end
```
Error during short read pre-preocessing. Please see /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/coverage_estimation/preprocess_reads.err /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/coverage_estimation/short_read_analysis.out /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/coverage_estimation/short_read_analysis.err for details.
```

And finally the short_read_analysis.err gives this

```
/mnt/cive/cancer/hassembly/OPERA-MS/test_files/..//tools_opera_ms//samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
Loading contigs from /mnt/cive/cancer/hassembly/OPERA-MS/test_files/contigs.fasta...
Analyzing 1 library: /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/read_mapping/opera.bam
min library mean : 0
minimum contig length is 500
Current library: 1 out of 1

```
which seems like a CPAN library issue

### 2) 
The file cmd_delta.txt is this one

```
 /mnt/cive/cancer/hassembly/OPERA-MS/test_files/..//tools_opera_ms//MUMmer3.23//nucmer --nosimplify --maxmatch -p /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/mummer/split_1.fa_split_1.fa /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/REF/split_1.fa /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/QUERY/split_1.fa > /dev/null 2> /dev/null
 /mnt/cive/cancer/hassembly/OPERA-MS/test_files/..//tools_opera_ms//MUMmer3.23//nucmer --nosimplify --maxmatch -p /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/mummer/split_2.fa_split_1.fa /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/REF/split_2.fa /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/QUERY/split_1.fa > /dev/null 2> /dev/null
 /mnt/cive/cancer/hassembly/OPERA-MS/test_files/..//tools_opera_ms//MUMmer3.23//nucmer --nosimplify --maxmatch -p /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/mummer/split_3.fa_split_1.fa /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/REF/split_3.fa /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/QUERY/split_1.fa > /dev/null 2> /dev/null
```

Trying the first line gives me this

```
/mnt/cive/cancer/hassembly/OPERA-MS/test_files/..//tools_opera_ms//MUMmer3.23//nucmer --nosimplify --maxmatch -p /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/mummer/split_1.fa_split_1.fa /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/REF/split_1.fa /mnt/cive/cancer/hassembly/OPERA-MS/test_files/RESULTS//intermediate_files/opera_long_read/GAPFILLING/TILLING/QUERY/split_1.fa 
-bash: /mnt/cive/cancer/hassembly/OPERA-MS/test_files/..//tools_opera_ms//MUMmer3.23//nucmer: /home/corongoyo/.local/miniconda/envs/andresoperams/bin/perl: bad interpreter: No such file or directory
```
Cheers

**Comment by jsgounot** [comment]
Hi,

1. for samtools it looks like your error is because you missed libncurses.so.5. You can install this dependency individually. Anyway, if it works I guess it's ok.

2. As indicated, your computer is not able to find your perl executable at `/home/corongoyo/.local/miniconda/envs/andresoperams/bin/perl` which is used to run nucmer. Maybe this is linked to your cluster configuration if you use one. You can try to recompile the mummer directory to fix this.

JS

**Comment by drelo** [comment]
Thanks for your help.
1) I used conda for ncurses
2)  perl is in that location, which perl finds it.  I copied it from there
to the tools folder in a previous step too. I guess a conda installation
has a problem deciding which version of perl or library is used.
Best regards
A

**Comment by drelo** [comment]
I think I made it work. thanks for your help.

```
mamba create -n andresOPERA
conda activate andresOPERA
mamba install -c compbiocore perl-switch perl==5.26.2
mamba install -y conda-forge::ncurses==5.9.0
mamba install -c bioconda perl-file-which perl-statistics-basic perl-statistics-r perl-app-cpanminus
git clone https://github.com/CSB5/OPERA-MS.git
cd OPERA-MS
make
ln -s $(which perl) tools_opera_ms/perl
```
I removed `samtools` and then I did a similar trick replacing it for the conda one
`ln -s ~/.local/miniconda/envs/andresOPERA/bin/samtools ./tools_opera_ms/
`
```
[Wed Mar  9 15:49:48 2022]	Assembly stats
Number of contigs: 498 
Assembly size: 9492161 bp
Max contig size: 997828 bp
Contig(s) longer than 1Mbp: 0 
Contig(s) longer than 500kbp: 5
Contig(s) longer than 100kbp: 19
Contig N50: 391199 bp

```

**Comment by cimaclean** [comment]
Hello, 

Running into the same errors as @drelo (specifically issue raised in https://github.com/CSB5/OPERA-MS/issues/72#issuecomment-1061360572). 

I'm running opera-ms on a shared cluster so don't have control over the opera-ms module. 

short_read_analysis.err gives:

> /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/opera-ms/0.9.0-20200802//tools_opera_ms//samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
Loading contigs from /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms_out/intermediate_files/megahit_assembly/final.contigs.fa...
Analyzing 1 library: /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms_out//intermediate_files/read_mapping/opera.bam
min library mean : 0
minimum contig length is 500
Current library: 1 out of 1

I'm confident it's the same type of error but unsure how to fix it for my circumstance. 

Thank you!
Best,
Charlotte

**Comment by jsgounot** [comment]
Hi Charlotte,

You either need to install the missing dependencies (libncurses) or install a new samtools (e.g. via conda) and replace the executable in the OPERA-MS directory. Sadly I don't have time to package OPERA-MS within a conda.

Hope this helps,
JS

**Comment by cimaclean** [comment]
Hi JS, 

Thanks for the speedy response - I will update if this works. 

Charlotte

**Comment by cimaclean** [comment]
Hi JS, 

Installing a new samtools (1.18) fixed my immediate problem. 

**New issue arose at the Gap filling [8/9] step.** 

There is a nucmer.error 

`Error in during gap_filling. Please see /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/gap_filling.err for details.`

gap_filling.err: 

`Error during tilling generation. Please see /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/TILLING/tilling_1.out and /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/TILLING/tilling_1.err for details.`

tilling_1.err:

```
rm -r /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/TILLING/QUERY /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/TILLING/REF
rm: cannot remove '/project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/TILLING/QUERY': No such file or directory
rm: cannot remove '/project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/TILLING/REF': No such file or directory
mkdir /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/TILLING/REF
 *** split /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/TILLING/consensus.fa
Use of uninitialized value $genome in print at /home/cmaclean/scratch/OPERA-MS//OPERA-LG/bin//run_mummer_large_ref.pl line 152.
mkdir /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/TILLING/QUERY
 *** split /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/user_assembly/contigs.fasta
 *** run the mummer mapping
rm -r /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/mummer
rm: cannot remove '/project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/mummer': No such file or directory
mkdir /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/mummer
cat /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_out//intermediate_files/opera_long_read/GAPFILLING/mummer/cmd_delta.txt | xargs -I cmd --max-procs=32 bash -c cmd > /dev/null 

Error in during nucmer.
```

nucmer.error:
`
20250125|220258|234301| ERROR: mummer and/or mgaps returned non-zero`

Still trying to figure it out on my own based on other issues. Any help/direction would be appreciated! 

Best,
Charlotte

**Comment by cimaclean** [comment]
OK I am experimenting with adding more long reads (I suspect it is a sub-sampling error similar to what is mentioned in https://github.com/CSB5/OPERA-MS/issues/70#issuecomment-1451498665)

I was attempting to coax out low coverage but informative long reads that were discarded from a de novo long read assembly of an environmental sample. Maybe my use case just doesn't make sense for opera-ms. 

Still interested in the hybrid assembly that opera-ms will hopefully spit out! 

Will update. 

**UPDATE**
This did not work - same nucmer error. 
When I run a line from cmd_delta.txt:

```
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "/project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_allLR_allSR_out//intermediate_files/opera_long_read/GAPFILLING/mummer/split_1.fa_split_3.fa.ntref" /scratch/cmaclean/OPERA-MS/tools_opera_ms/MUMmer3.23/mummer: empty sequence in multiple fasta file
ERROR: mummer and/or mgaps returned non-zero
```

I highly doubt the issue is to do with not enough reads now. 

Charlotte

**Comment by jsgounot** [comment]
Hi Charlotte,

is `/project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_allLR_allSR_out//intermediate_files/opera_long_read/GAPFILLING/mummer/split_1.fa_split_3.fa.ntref` empty? Is it the case for most the input files in `cmd_delta.txt`?

JS

**Comment by cimaclean** [comment]
Hi JS, 

split_1.fa_split_3.fa.ntref is 203  B: 

`>allcontigs /project/6001594/BoggyLake/BLWA1-MetagenomeSeq-NEWPIPELINE/C_Assembly/C_ii_Hybrid_assembly/opera-ms-local_allLR_allSR_out/intermediate_files/opera_long_read/GAPFILLING/TILLING/REF/split_1.fa`


^^ the GAPFILLING/TILLING/REF/*.fa are empty 

Charlotte

**Comment by jsgounot** [comment]
This one will be hard to resolve like this. Is it possible for you to share either (a) the gapfilling directory or (b) the reads? Sorry about this.

**Comment by cimaclean** [comment]
Hi JS, 

I was able to get opera-ms to work just fine on a different machine. Maybe chalk it up to poor installation / dependency management on my part. 

Let me now if you are still interested in the error - otherwise we can close the issue. 

Charlotte

**Comment by jsgounot** [comment]
Hi Charlotte, glad to hear it works now. It's likely due to differences in samtools versions. No need to send me the files if this is working now. Good luck with your work!
