### ISSUE TITLE
Contigs vs scaffolds.

### ISSUE THREAD

**Issue by Unaimend** [CSB5/OPERA-MS#75]
OPERA-MS outputs a fille called contigs but are those really just contigs or are those scaffolds i.e. with N`s like SPAdes

**Comment by Unaimend** [comment]
I am asking because I am currently comparing OPERA-MS to SPAdes and it would be kind of "unfair" to compare contigs to scaffolds

**Comment by Unaimend** [comment]
Because there are gaps in the contigs.fasta 
![image](https://user-images.githubusercontent.com/7808379/220875735-d893e684-1ae0-4ecf-9bba-74d3ff28deeb.png)

**Comment by jsgounot** [comment]
Hi @Unaimend,

From [OPERA-MS paper](https://www.nature.com/articles/s41587-019-0191-2):

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/13219245/221071646-533902e0-fe41-4678-803e-50f18d62ad4a.png">

So yes, OPERA-MS contigs result from multiple [OPERA-LG exact scaffoldings](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0951-y). Note however that the way scaffolding is done is different between Spades and OPERA.

Regards,
JS

**Comment by Unaimend** [comment]
Thank you very much for the answer.
