### ISSUE TITLE
Missing parameter

### ISSUE THREAD

**Issue by Unaimend** [CSB5/OPERA-MS#77]
Hello OPERA-MS Team, 

Is there any way to specify the memory for the underlying short-read assembler?

**Comment by jsgounot** [comment]
Hi,

So far, no it's not an option. I guess you have this issue with Spades.
If you want a quick fix you can edit directly `OPERA-MS.pl` code [at line 535](https://github.com/CSB5/OPERA-MS/blob/OPERA-MS-0.9.0/OPERA-MS.pl#L521) and add a `--memory` option.

From `spades.py` help:
```
-m/--memory	<int>		RAM limit for SPAdes in Gb (terminates if exceeded)
				[default: 250] 
```

But I guess this will make your assembly extremely slow. 

Regards,
jsgounot

**Comment by Unaimend** [comment]
Thanks, that was my quick fix as well. Just out of interest, why do you think this would make my assembly extremely slow?

**Comment by jsgounot** [comment]
From experience, large graph are usually slow to be processed. Hopefully, this will not be your case.

**Comment by Unaimend** [comment]
Ahh ok. Well, our last assembly took more than two weeks :). This one is a little smaller(181 reference genomes, synthetic reads) just my Bsc. Thesis. Thank you for your help.
