### ISSUE TITLE
Cannot install OPERA-MS: makefile error

### ISSUE THREAD

**Issue by faye92sun** [CSB5/OPERA-MS#82]
My kernel is Linux 3.10.0-514.el7.x86_64. It is a shared server and I do not have sudo privileges. 
I have installed all the perl dependencies, but when I use
`make`
It shows an error:
```
cd SIGMA&&make;
make[1]: Entering directory `/lomi_home/mengqi/OPERA-MS/SIGMA'
g++ -std=c++0x -O3 -Wall -Wconversion  -c sigma.cpp
Assembler messages:
Error: can't open /tmp/ccFVXcS6.s for reading: No such file or directory
make[1]: *** [sigma.o] Error 1
make[1]: Leaving directory `/lomi_home/mengqi/OPERA-MS/SIGMA'
make: *** [sigma] Error 2
```
And when I run
`perl OPERA-MS.pl check-dependency`
It returns 
```
OPERA-LG found in /lomi_home/mengqi/OPERA-MS//OPERA-LG/bin/ is not functional. Checking path for OPERA-LG.
OPERA-LG not found in path. Exiting.
```
I have added said directory to the $PATH and it still returns the same error. Thus I cannot install OPERA-MS.
Any help would be appreciated. Thanks!

**Comment by jsgounot** [comment]
Hi Faye,

sorry to hear that. It's normal that the dependencies check does not work since you have a compilation issue first. Do you have access to your temp directory on you shared server? For example, can you do `touch /tmp/ccFVXcS6`?

JS

**Comment by faye92sun** [comment]
Thank you for your reply. I tried creating the file `/tmp/ccFVXcS6.s`, but the `make` error generates a random file name every time, regardless of whether I created the file in `/tmp`. Such as: 
```
cd SIGMA&&make;
make[1]: Entering directory `/lomi_home/mengqi/OPERA-MS/SIGMA'
g++ -std=c++0x -O3 -Wall -Wconversion  -c sigma.cpp
Assembler messages:
Error: can't open /tmp/cc2HQpzD.s for reading: No such file or directory
make[1]: *** [sigma.o] Error 1
make[1]: Leaving directory `/lomi_home/mengqi/OPERA-MS/SIGMA'
make: *** [sigma] Error 2
```
And if I use `make` again immediately, it returns:
```
cd SIGMA&&make;
make[1]: Entering directory `/lomi_home/mengqi/OPERA-MS/SIGMA'
g++ -std=c++0x -O3 -Wall -Wconversion  -c sigma.cpp
Assembler messages:
Error: can't open /tmp/ccT2JHKV.s for reading: No such file or directory
make[1]: *** [sigma.o] Error 1
make[1]: Leaving directory `/lomi_home/mengqi/OPERA-MS/SIGMA'
make: *** [sigma] Error 2
```
So changing `/tmp` doesn't seem to work.

**Comment by jsgounot** [comment]
Yes, it is normal that `make` creates temporary files with different names each time. Were you able to manually create a file in `/tmp/` without error using the touch command? It seems that make does not have the right to access your temp directory. If this is the case, you might want to talk to your sys admin, maybe he would be able to resolve this issue for you.

**Comment by faye92sun** [comment]
Yes I was able to manually create a file in `/tmp`, so access to `/tmp` shouldn't be the issue here.

**Comment by jsgounot** [comment]
This is interesting, it seems to be a compilation issue from g++. Maybe doing something [like this](https://stackoverflow.com/questions/49696709/gcc-assembler-messages-cant-open-tmp-ccqjy5hv-s-for-reading-no-such-file-or-di) might work. In the Makefile, try to add `-pipe` to the sigma CFLAGS ([line 2](https://github.com/CSB5/OPERA-MS/blob/OPERA-MS-0.9.0/SIGMA/Makefile#L2)). 

Could you share your G++ version for reference: `g++ --version`?

**Comment by faye92sun** [comment]
I added `-pipe` to the `SIGMA/Makefile` and running `make` still generates errors
```
cd SIGMA&&make;
make[1]: Entering directory `/lomi_home/mengqi/OPERA-MS/SIGMA'
make[1]: Warning: File `Makefile' has modification time 377 s in the future
g++ -std=c++0x -O3 -Wall -Wconversion -pipe -c sigma.cpp
g++ -std=c++0x -O3 -Wall -Wconversion -pipe -c contig_reader.cpp
g++ -std=c++0x -O3 -Wall -Wconversion -pipe -c mapping_reader.cpp
g++ -std=c++0x -O3 -Wall -Wconversion -pipe -c edge_reader.cpp
g++ -std=c++0x -O3 -Wall -Wconversion -pipe -c contig.cpp
g++ -std=c++0x -O3 -Wall -Wconversion -pipe -c edge.cpp
g++ -std=c++0x -O3 -Wall -Wconversion -pipe -c cluster.cpp
g++ -std=c++0x -O3 -Wall -Wconversion -pipe -c cluster_graph.cpp
g++ -std=c++0x -O3 -Wall -Wconversion -pipe -c probability_distribution.cpp
g++ -std=c++0x -O3 -Wall -Wconversion -pipe sigma.o contig_reader.o mapping_reader.o edge_reader.o contig.o edge.o cluster.o cluster_graph.o probability_distribution.o -o ../bin/sigma
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Leaving directory `/lomi_home/mengqi/OPERA-MS/SIGMA'
cd OPERA-LG&&make install;
make[1]: Entering directory `/lomi_home/mengqi/OPERA-MS/OPERA-LG'
cd src; sed -i "s/int Configure::MAX_NUMBER_OF_PARTIAL_SCAFFOLDS = 10000000;/int Configure::MAX_NUMBER_OF_PARTIAL_SCAFFOLDS = 100000;/" Configure.cpp; sed -i "s/int Configure::PERCENTAGE_OF_INCREASING_THRESHOLD_GRAPHS = 1;/int Configure::PERCENTAGE_OF_INCREASING_THRESHOLD_GRAPHS = 5;/" Configure.cpp;make install; mv ../bin/OPERA-LG ../bin/OPERA-LG-fast; sed -i "s/int Configure::MAX_NUMBER_OF_PARTIAL_SCAFFOLDS = 100000;/int Configure::MAX_NUMBER_OF_PARTIAL_SCAFFOLDS = 10000000;/" Configure.cpp; sed -i "s/int Configure::PERCENTAGE_OF_INCREASING_THRESHOLD_GRAPHS = 5;/int Configure::PERCENTAGE_OF_INCREASING_THRESHOLD_GRAPHS = 1;/" Configure.cpp;make install;
make[2]: Entering directory `/lomi_home/mengqi/OPERA-MS/OPERA-LG/src'
g++ -std=c++0x -O3 -Wall -Wno-deprecated -c Array.cpp
Assembler messages:
Error: can't open /tmp/cca5wwMQ.s for reading: No such file or directory
make[2]: *** [Array.o] Error 1
make[2]: Leaving directory `/lomi_home/mengqi/OPERA-MS/OPERA-LG/src'
mv: cannot stat '../bin/OPERA-LG': No such file or directory
make[2]: Entering directory `/lomi_home/mengqi/OPERA-MS/OPERA-LG/src'
g++ -std=c++0x -O3 -Wall -Wno-deprecated -c Array.cpp
Assembler messages:
Error: can't open /tmp/ccmt2eiy.s for reading: No such file or directory
make[2]: *** [Array.o] Error 1
make[2]: Leaving directory `/lomi_home/mengqi/OPERA-MS/OPERA-LG/src'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/lomi_home/mengqi/OPERA-MS/OPERA-LG'
make: *** [opera] Error 2
```
Here is my g++ version for reference
```
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
```

**Comment by jsgounot** [comment]
Ok, the good news is that it seems it worked, the bad news is that you will probably need to do it for all makefiles. You'll probably need it for [OPERA-LG makefile](https://github.com/CSB5/OPERA-MS/blob/OPERA-MS-0.9.0/OPERA-LG/src/Makefile#L6) and the [short-reads analysis](https://github.com/CSB5/OPERA-MS/blob/OPERA-MS-0.9.0/SHORT_READ_ANALYSIS/src/Makefile) as well, at the beginning of the file, not the debug though.

**Comment by faye92sun** [comment]
I added `-pipe` to those makefiles and it seems to have solved the problem, thanks!
