### ISSUE TITLE
Short reads only

### ISSUE THREAD

**Issue by steven-bioinfo** [CSB5/OPERA-MS#86]
Hello,

Has your software ever been tested and evaluated on illumina short  reads only?
I want to assemble an ecosystem with several strains of the same species, but the standard assembly tools don't allow me to discriminate between the strains correctly.
According to the literature, recent tools like yours are all based on long reads and not for short reads.

Thank you for your help,

Steven

**Comment by jsgounot** [comment]
Hi Steven,

OPERA-MS is only an hybrid assembler and does not work with short-reads only. If you want to assemble several strains from the same species, I'd recommand you to use dedicated tools that would work after or similar to an assembly, such as [StrainXPress](https://github.com/kangxiongbin/StrainXpress) or our recent tool [Floria](https://github.com/bluenote-1577/floria). I recommend using MEGAHIT as an initial short-reads assembler for phasing tool that need an assembly prior to the phasing.

I'm hoping this answer your questions,
jsgounot

**Comment by steven-bioinfo** [comment]
Thanks for our reply, I will test our recent tool Floria

What software do you recommend for the alignment and the variant detection ?

**Comment by jsgounot** [comment]
Alignement and variant calling choice will depend of your goals. I'd recommend you to check the litterature as multiple pipelines are now available for such tasks.
