### ISSUE TITLE
problems when running test

### ISSUE THREAD

**Issue by chen318liang** [CSB5/OPERA-MS#9]
.......
.......
wget --no-check-certificate -O /home/wangjun/software/OPERA-MS//genomeDB_Sketch.msh https://www.dropbox.com/s/kot086vh26nds6j/genomeDB_Sketch.msh?dl=0
--2018-11-22 16:02:04--  https://www.dropbox.com/s/kot086vh26nds6j/genomeDB_Sketch.msh?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 199.16.156.7
Connecting www.dropbox.com (www.dropbox.com)|199.16.156.7|:443... failed：Connection refused。

wget --no-check-certificate -O /home/wangjun/software/OPERA-MS//complete_ref_genomes.tar.gz https://www.dropbox.com/s/wcxvy2u0yhp3pw0/complete_ref_genomes.tar.gz?dl=0
--2018-11-22 16:02:04--  https://www.dropbox.com/s/wcxvy2u0yhp3pw0/complete_ref_genomes.tar.gz?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 199.16.156.7
Connecting www.dropbox.com (www.dropbox.com)|199.16.156.7|:443... failed：Connection refused。
......
......
Error in during reference based clustering. Please see /home/wangjun/software/OPERA-MS/sample_output//intermediate_files/reference_mapping/log.err for details.

**Comment by lch14forever** [comment]
Dropbox is blocked by GFW in China. Please use VPN or download the required references from my 微云: https://share.weiyun.com/5dBj6T6 .

**Comment by chen318liang** [comment]
ok! thanks very much! I will try!

**Comment by chen318liang** [comment]
> Dropbox is blocked by GFW in China. Please use VPN or download the required references from my 微云: https://share.weiyun.com/5dBj6T6 .
I also can not download it from 微云: https://share.weiyun.com/5dBj6T6. it always shows "download failed" Any other ways?

**Comment by lch14forever** [comment]
Is figshare available in China? https://figshare.com.

**Comment by chen318liang** [comment]
I did not use this before. But I can open this web.

**Comment by chen318liang** [comment]
I can download other files from 微云. could you upload the files again? maybe it was damaged!
